-- Catalogo de tinciones para seleccion en formularios

CREATE TABLE IF NOT EXISTS public.tinciones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL UNIQUE,
  sort_order INTEGER NOT NULL DEFAULT 0,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_tinciones_sort_order ON public.tinciones(sort_order ASC, nombre ASC);

INSERT INTO public.tinciones (nombre, sort_order, activo)
VALUES
  ('H&E', 10, TRUE),
  ('Tricrómico de Masson', 20, TRUE),
  ('Fontana Masson', 30, TRUE),
  ('Grocott', 40, TRUE),
  ('Papanicolaou', 50, TRUE),
  ('Wright/Giemsa', 60, TRUE),
  ('Inmunohistoquímica', 70, TRUE),
  ('Azul alcián', 80, TRUE),
  ('Reticulina', 90, TRUE),
  ('Metanamina de Jones', 100, TRUE),
  ('PAS', 110, TRUE)
ON CONFLICT (nombre) DO NOTHING;

GRANT SELECT ON TABLE public.tinciones TO anon, authenticated;
