-- Créditos del Atlas: fotografías destacadas y colaboradores históricos.
-- Ejecutar en Supabase después de security_hardening.sql.

BEGIN;

CREATE TABLE IF NOT EXISTS public.credit_profiles (
  profile_key text PRIMARY KEY CHECK (profile_key IN ('developer', 'microscopy_coordinator')),
  photo_url text,
  updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO public.credit_profiles (profile_key)
VALUES ('developer'), ('microscopy_coordinator')
ON CONFLICT (profile_key) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.credit_contributors (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL CHECK (length(trim(name)) BETWEEN 2 AND 160),
  start_year integer NOT NULL CHECK (start_year BETWEEN 1900 AND 2200),
  end_year integer CHECK (end_year BETWEEN 1900 AND 2200),
  is_current boolean NOT NULL DEFAULT false,
  contribution text CHECK (contribution IS NULL OR length(trim(contribution)) <= 600),
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT credit_contributors_period_check CHECK (
    (is_current = true AND end_year IS NULL)
    OR (is_current = false AND end_year IS NOT NULL AND end_year >= start_year)
  )
);

CREATE INDEX IF NOT EXISTS idx_credit_contributors_sort
  ON public.credit_contributors (sort_order, name);

ALTER TABLE public.credit_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.credit_contributors ENABLE ROW LEVEL SECURITY;

GRANT SELECT ON public.credit_profiles, public.credit_contributors TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON public.credit_profiles, public.credit_contributors TO anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.credit_contributors_id_seq TO anon, authenticated;

DROP POLICY IF EXISTS credits_public_read ON public.credit_profiles;
CREATE POLICY credits_public_read ON public.credit_profiles FOR SELECT USING (true);
DROP POLICY IF EXISTS credits_admin_insert ON public.credit_profiles;
CREATE POLICY credits_admin_insert ON public.credit_profiles FOR INSERT
  WITH CHECK (public.atlas_has_role(ARRAY['Administrador']));
DROP POLICY IF EXISTS credits_admin_update ON public.credit_profiles;
CREATE POLICY credits_admin_update ON public.credit_profiles FOR UPDATE
  USING (public.atlas_has_role(ARRAY['Administrador']))
  WITH CHECK (public.atlas_has_role(ARRAY['Administrador']));
DROP POLICY IF EXISTS credits_admin_delete ON public.credit_profiles;
CREATE POLICY credits_admin_delete ON public.credit_profiles FOR DELETE
  USING (public.atlas_has_role(ARRAY['Administrador']));

DROP POLICY IF EXISTS credits_public_read ON public.credit_contributors;
CREATE POLICY credits_public_read ON public.credit_contributors FOR SELECT USING (true);
DROP POLICY IF EXISTS credits_admin_insert ON public.credit_contributors;
CREATE POLICY credits_admin_insert ON public.credit_contributors FOR INSERT
  WITH CHECK (public.atlas_has_role(ARRAY['Administrador']));
DROP POLICY IF EXISTS credits_admin_update ON public.credit_contributors;
CREATE POLICY credits_admin_update ON public.credit_contributors FOR UPDATE
  USING (public.atlas_has_role(ARRAY['Administrador']))
  WITH CHECK (public.atlas_has_role(ARRAY['Administrador']));
DROP POLICY IF EXISTS credits_admin_delete ON public.credit_contributors;
CREATE POLICY credits_admin_delete ON public.credit_contributors FOR DELETE
  USING (public.atlas_has_role(ARRAY['Administrador']));

COMMIT;
