-- Catalogo de tinciones para seleccion en formularios

CREATE TABLE IF NOT EXISTS public.tinciones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL UNIQUE,
  sort_order INTEGER NOT NULL DEFAULT 0,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_tinciones_sort_order ON public.tinciones(sort_order ASC, nombre ASC);

INSERT INTO public.tinciones (nombre, sort_order, activo)
VALUES
  ('H&E', 10, TRUE),
  ('Tricrómico de Masson', 20, TRUE),
  ('Fontana Masson', 30, TRUE),
  ('Grocott', 40, TRUE),
  ('Papanicolaou', 50, TRUE),
  ('Wright/Giemsa', 60, TRUE),
  ('Inmunohistoquímica', 70, TRUE),
  ('Azul alcián', 80, TRUE),
  ('Reticulina', 90, TRUE),
  ('Metanamina de Jones', 100, TRUE),
  ('PAS', 110, TRUE)
ON CONFLICT (nombre) DO NOTHING;

ALTER TABLE public.tinciones ENABLE ROW LEVEL SECURITY;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.tinciones TO anon, authenticated;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'tinciones'
      AND policyname = 'Permitir lectura de tinciones'
  ) THEN
    CREATE POLICY "Permitir lectura de tinciones"
      ON public.tinciones
      FOR SELECT
      USING (true);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'tinciones'
      AND policyname = 'Permitir insercion de tinciones'
  ) THEN
    CREATE POLICY "Permitir insercion de tinciones"
      ON public.tinciones
      FOR INSERT
      WITH CHECK (true);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'tinciones'
      AND policyname = 'Permitir actualizacion de tinciones'
  ) THEN
    CREATE POLICY "Permitir actualizacion de tinciones"
      ON public.tinciones
      FOR UPDATE
      USING (true)
      WITH CHECK (true);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'tinciones'
      AND policyname = 'Permitir eliminacion de tinciones'
  ) THEN
    CREATE POLICY "Permitir eliminacion de tinciones"
      ON public.tinciones
      FOR DELETE
      USING (true);
  END IF;
END $$;
