import React from 'react';
import {
  Microscope,
  ShieldCheck,
  ShieldAlert,
  Shield,
  ArrowRightLeft,
  Filter,
  Sparkles,
  Droplets,
  Droplet,
  Layers,
  Wind,
  Waves,
  Zap,
  Activity,
  Scan,
  Palette,
  Pipette,
  MapPin,
  BadgeCheck,
  Star,
  Download,
  Sun,
  Target,
  Crosshair,
  Grid,
  Network,
  Cpu,
  Fingerprint,
  Lightbulb,
  Search,
  Share2,
  Atom,
  Heart,
  Eye,
  BicepsFlexed,
} from 'lucide-react';
import {
  FaLungs,
  FaLungsVirus,
  FaBrain,
  FaBone,
  FaBacteria,
  FaVirus,
  FaVirusCovid,
  FaSyringe,
  FaStethoscope,
  FaHeartPulse,
  FaHeart,
  FaHospital,
  FaEye,
  FaEarListen,
  FaTooth,
  FaWeightScale,
  FaDroplet,
  FaVial,
  FaShieldHeart,
  FaHandHoldingMedical,
  FaNotesMedical,
  FaStaffSnake,
  FaVenus,
  FaMars,
  FaVenusMars,
  FaPersonPregnant,
  FaPersonBreastfeeding,
  FaBaby,
  FaBabyCarriage,
  FaBottleDroplet,
  FaDumbbell,
  FaShieldVirus,
  FaEyeLowVision,
} from 'react-icons/fa6';
import {
  GiKidneys,
  GiStomach,
  GiLiver,
  GiHeartOrgan,
  GiMuscleUp,
  GiSpineArrow,
  GiBlood,
  GiChemicalDrop,
  GiFunnel,
  GiInternalOrgan,
  GiRibcage,
  GiSkullCrossedBones,
  GiSkeleton,
  GiJoint,
  GiArmBandage,
  GiEyeball,
  GiNoseFront,
  GiMouthWatering,
  GiMicroscopeLens,
  GiMicroscope,
  GiDna2,
  GiDna1,
  GiProtectionGlasses,
  GiBrickWall,
  GiLayeredArmor,
  GiHexagonalNut,
  GiWaterFlask,
  GiFat,
  GiOilySpiral,
  GiMeat,
  GiBoneKnife,
  GiBrain,
  GiHeartDrop,
  GiBiceps,
  GiMuscleFat,
  GiFingerPrint,
  GiLungs,
  GiBubblingFlask,
  GiCellarBarrels,
  GiTooth,
  GiTongue,
  GiFetus,
  GiEggPod,
  GiRawEgg,
  GiBabyBottle,
  GiShinyIris,
  GiStarPupil,
  GiMazeCornea,
  GiBowels,
  GiEating,
  GiCrossedAirFlows,
  GiAirZigzag,
  GiHumanEar,
  GiBrokenBone,
  GiLeg,
  GiArm,
  GiSprint,
  GiDropletSplash,
  GiWaterDrop,
  GiChestArmor,
  GiMilkCarton,
  GiAllSeeingEye,
  GiLipstick,
  GiOpenWound,
  GiWindSlap,
  GiDroplets,
  GiMucousPillar,
  GiOrganigram,
} from 'react-icons/gi';
import {
  TbGridPattern,
  TbBorderAll,
  TbDropletFilled,
  TbDropletHalf2,
  TbBone,
  TbBoneFilled,
  TbBoneOff,
  TbBrain,
  TbNetwork,
  TbTestPipe,
  TbDeviceHeartMonitor,
  TbFingerprint,
  TbLungs,
  TbDental,
  TbGenderMale,
  TbGenderFemale,
  TbBabyBottle,
  TbMilk,
  TbMicroscope,
  TbZoomIn,
  TbApple,
  TbActivityHeartbeat,
} from 'react-icons/tb';

export type HistologyTopicCategory =
  | 'all'
  | 'epitelios'
  | 'glandulas'
  | 'microscopios'
  | 'adiposo'
  | 'hueso'
  | 'cartilago'
  | 'nervioso'
  | 'sangre'
  | 'linfoide'
  | 'musculo'
  | 'cardiovascular'
  | 'tegumentario'
  | 'respiratorio'
  | 'digestivo'
  | 'oral'
  | 'anexas'
  | 'urinario'
  | 'reproductor'
  | 'mamaria'
  | 'ojo'
  | 'otros';

/**
 * Orden estricto de los temas según la solicitud del usuario:
 * 1 a 20 los temas histológicos requeridos, seguidos aparte por 'otros' (tinciones y diagnóstico).
 */
export const ORDERED_HISTOLOGY_TOPICS: HistologyTopicCategory[] = [
  'epitelios',
  'glandulas',
  'microscopios',
  'adiposo',
  'hueso',
  'cartilago',
  'nervioso',
  'sangre',
  'linfoide',
  'musculo',
  'cardiovascular',
  'tegumentario',
  'respiratorio',
  'digestivo',
  'oral',
  'anexas',
  'urinario',
  'reproductor',
  'mamaria',
  'ojo',
  'otros',
];

export const HISTOLOGY_TOPIC_LABELS: Record<HistologyTopicCategory, { label: string; icon: string }> = {
  all: { label: 'Todos los Íconos', icon: '🌟' },
  epitelios: { label: 'Epitelios', icon: '🧱' },
  glandulas: { label: 'Glándulas Endocrinas y Exocrinas', icon: '🧪' },
  microscopios: { label: 'Microscopios', icon: '🔬' },
  adiposo: { label: 'Tejido Adiposo', icon: '🧈' },
  hueso: { label: 'Hueso', icon: '🦴' },
  cartilago: { label: 'Cartílago', icon: '🦻' },
  nervioso: { label: 'Sistema Nervioso', icon: '🧠' },
  sangre: { label: 'Sangre', icon: '🩸' },
  linfoide: { label: 'Sistema Linfoide e Inmunidad', icon: '🛡️' },
  musculo: { label: 'Músculo', icon: '💪' },
  cardiovascular: { label: 'Sistema Cardiovascular', icon: '🫀' },
  tegumentario: { label: 'Sistema Tegumentario (Piel)', icon: '👆' },
  respiratorio: { label: 'Sistema Respiratorio', icon: '🫁' },
  digestivo: { label: 'Sistema Digestivo', icon: '🥣' },
  oral: { label: 'Cavidad Oral', icon: '👄' },
  anexas: { label: 'Glándulas Anexas del Sistema Digestivo', icon: '🧫' },
  urinario: { label: 'Sistema Urinario', icon: '💧' },
  reproductor: { label: 'Sistema Reproductor Masculino y Femenino', icon: '🧬' },
  mamaria: { label: 'Glándula Mamaria', icon: '🍼' },
  ojo: { label: 'Ojo y Sentidos Especiales', icon: '👁️' },
  otros: { label: 'Otros (Tinciones y Diagnóstico)', icon: '🩺' },
};

/**
 * Sinónimos y términos de búsqueda asociados a cada tema histológico.
 * Se normalizan automáticamente sin acentos para búsquedas instantáneas.
 */
export const HISTOLOGY_TOPIC_SYNONYMS: Record<HistologyTopicCategory, string[]> = {
  all: ['todo', 'todos', 'general', 'medico', 'clinico'],
  otros: ['otros', 'otro', 'tincion', 'tinciones', 'diagnostico', 'diagnóstico', 'clinica', 'clínica', 'patologia', 'patología', 'h&e', 'adn', 'marcador', 'hospital', 'biopsia', 'calidad', 'estrella', 'foco'],
  epitelios: ['epitelio', 'epitelios', 'epitelial', 'revestimiento', 'simple', 'estratificado', 'queratina', 'basal', 'endotelio', 'mesotelio', 'cilios', 'microvellosidad', 'microvellosidades', 'plano', 'cubico', 'cilindrico', 'pseudoestratificado'],
  glandulas: ['glandula', 'glandulas', 'glándula', 'glándulas', 'endocrina', 'endocrinas', 'exocrina', 'exocrinas', 'tiroides', 'hormona', 'hormonas', 'secrecion', 'secreción', 'acino', 'acinos', 'adenomero', 'paratiroides', 'suprarrenal', 'hipofisis'],
  microscopios: ['microscopio', 'microscopios', 'microscopia', 'microscopía', 'optico', 'óptico', 'lente', 'lentes', 'objetivo', 'objetivos', 'aumento', 'resolucion', 'resolución', 'inmersion', 'inmersión', 'fotomicrografia', 'fotomicrografía', 'placa', 'laminilla', 'campo', 'enfoque'],
  adiposo: ['adiposo', 'adiposos', 'grasa', 'grasas', 'adipocito', 'adipocitos', 'lipido', 'lipidos', 'lípido', 'lípidos', 'parda', 'blanca', 'unilocular', 'multilocular', 'paniculo', 'trigliceridos', 'graso'],
  hueso: ['hueso', 'huesos', 'oseo', 'oseos', 'óseo', 'óseos', 'esqueleto', 'esqueletos', 'osteocito', 'osteocitos', 'osteoblasto', 'osteoblastos', 'osteoclasto', 'osteoclastos', 'havers', 'trabecula', 'trabécula', 'compacto', 'esponjoso', 'vertebra', 'vértebra', 'columna', 'craneo', 'cráneo'],
  cartilago: ['cartilago', 'cartilagos', 'cartílago', 'cartílagos', 'condrocito', 'condrocitos', 'hialino', 'elastico', 'elástico', 'fibrocartilago', 'fibrocartílago', 'pericondrio', 'articulacion', 'articulación', 'menisco', 'meniscos', 'oreja', 'tabique'],
  nervioso: ['nervio', 'nervios', 'nervioso', 'nerviosos', 'neurona', 'neuronas', 'axon', 'axón', 'dendrita', 'dendritas', 'sinapsis', 'cerebro', 'cerebros', 'medula', 'médula', 'glia', 'glía', 'astrocito', 'astrocitos', 'mielina', 'schwann', 'encefalo', 'encéfalo'],
  sangre: ['sangre', 'sanguineo', 'sanguíneo', 'sanguineos', 'hematologia', 'hematología', 'eritrocito', 'eritrocitos', 'globulo', 'glóbulo', 'leucocito', 'leucocitos', 'plaqueta', 'plaquetas', 'frotis', 'plasma', 'hematocrito', 'hemoglobina', 'vial', 'hematies'],
  linfoide: ['linfoide', 'linfoides', 'linfatico', 'linfático', 'linfocito', 'linfocitos', 'ganglio', 'ganglios', 'bazo', 'timo', 'inmune', 'inmunidad', 'anticuerpo', 'anticuerpos', 'defensa', 'malt', 'peyer', 'fagocito', 'macrófago', 'macrofago'],
  musculo: ['musculo', 'musculos', 'músculo', 'músculos', 'muscular', 'musculares', 'estriado', 'esqueletico', 'esquelético', 'liso', 'cardiaco', 'cardíaco', 'sarcomero', 'sarcómero', 'actina', 'miosina', 'biceps', 'bíceps', 'miofibrilla', 'contraccion', 'contracción'],
  cardiovascular: ['cardiovascular', 'cardiovasculares', 'corazon', 'corazones', 'corazón', 'cardiaco', 'cardíaco', 'vaso', 'vasos', 'arteria', 'arterias', 'vena', 'venas', 'capilar', 'capilares', 'endotelio', 'pulso', 'valvula', 'válvula', 'miocardio', 'epicardio', 'endocardio'],
  tegumentario: ['tegumentario', 'tegumento', 'piel', 'dermis', 'epidermis', 'hipodermis', 'cutaneo', 'cutáneo', 'estrato', 'corneo', 'córneo', 'melanocito', 'melanocitos', 'queratinocito', 'foliculo', 'folículo', 'huella', 'dermatoglifo'],
  respiratorio: ['respiratorio', 'respiratorios', 'pulmon', 'pulmones', 'pulmón', 'alveolo', 'alveolos', 'alvéolo', 'alvéolos', 'traquea', 'traqueas', 'tráquea', 'tráqueas', 'bronquio', 'bronquios', 'aire', 'oxigeno', 'oxígeno', 'ventilacion', 'ventilación', 'nariz', 'hematosis'],
  digestivo: ['digestivo', 'digestivos', 'digestion', 'digestión', 'estomago', 'estomagos', 'estómago', 'estómagos', 'intestino', 'intestinos', 'duodeno', 'yeyuno', 'ileon', 'íleon', 'colon', 'esofago', 'esófago', 'gastrico', 'gástrico', 'peristalsis', 'mucosa'],
  oral: ['oral', 'orales', 'boca', 'diente', 'dientes', 'lengua', 'encia', 'encias', 'encía', 'encías', 'saliva', 'salival', 'gusto', 'paladar', 'esmalte', 'dentina', 'labio', 'labios', 'papila', 'papilas', 'odontoblasto'],
  anexas: ['anexas', 'anexa', 'higado', 'higados', 'hígado', 'hígados', 'pancreas', 'páncreas', 'vesicula', 'vesícula', 'biliar', 'biliares', 'hepatocito', 'hepatocitos', 'islas', 'langerhans', 'parotida', 'parótida', 'salivales'],
  urinario: ['urinario', 'urinarios', 'rinon', 'rinones', 'riñon', 'riñones', 'riñón', 'riñones', 'nefrona', 'nefronas', 'glomerulo', 'glomérulo', 'podocito', 'podocitos', 'orina', 'vejiga', 'ureter', 'uréter', 'caliz', 'cáliz', 'filtracion', 'filtración'],
  reproductor: ['reproductor', 'reproductores', 'reproduccion', 'reproducción', 'masculino', 'femenino', 'testiculo', 'testiculos', 'testículo', 'testículos', 'ovario', 'ovarios', 'utero', 'útero', 'espermatozoide', 'espermatozoides', 'ovocito', 'ovocitos', 'gameto', 'fertilizacion', 'foliculo'],
  mamaria: ['mamaria', 'mamarias', 'mama', 'mamas', 'seno', 'senos', 'pecho', 'pechos', 'lactancia', 'leche', 'galactoforo', 'galactóforo', 'pezon', 'pezón', 'alveolo', 'alvéolo', 'prolactina', 'oxitocina'],
  ojo: ['ojo', 'ojos', 'ocular', 'oculares', 'retina', 'cornea', 'córnea', 'cristalino', 'iris', 'pupila', 'pupilas', 'esclera', 'vision', 'visión', 'optico', 'óptico', 'fovea', 'fóvea', 'bastones', 'conos', 'esclerotica'],
};

/**
 * Quita acentos/diacríticos y pasa a minúsculas
 */
export function normalizeSearchTerm(str: string): string {
  return (str || '')
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .trim();
}

/**
 * Genera variantes del término (singular/plural) para español
 */
export function getTermVariations(term: string): string[] {
  const norm = normalizeSearchTerm(term);
  if (!norm) return [];
  const set = new Set<string>([norm]);

  // Si termina en "es" (ej: pulmones -> pulmon, rinones -> rinon, canales -> canal)
  if (norm.length > 3 && norm.endsWith('es')) {
    set.add(norm.slice(0, -2));
  }
  // Si termina en "s" (ej: huesos -> hueso, ojos -> ojo, celulas -> celula)
  if (norm.length > 2 && norm.endsWith('s')) {
    set.add(norm.slice(0, -1));
  }
  // Variantes inversas (añadir s o es)
  set.add(norm + 's');
  set.add(norm + 'es');

  return Array.from(set);
}

export interface MedicalIconDefinition {
  id: string;
  name: string;
  category: 'anatomy' | 'physiology' | 'lab' | 'clinical';
  topic: HistologyTopicCategory;
  keywords: string[];
  render: (props: { size?: number; className?: string; style?: React.CSSProperties; color?: string }) => React.ReactElement;
}

export const MEDICAL_ICONS_CATALOG: MedicalIconDefinition[] = [
  // ══════════════════════════════════════════════════════════════════════════
  // 1. 🧱 EPITELIOS (10 íconos)
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 'layers',
    name: 'Estratificación / Láminas Basales',
    category: 'physiology',
    topic: 'epitelios',
    keywords: ['epitelio', 'epitelios', 'estrato', 'capas', 'laminas', 'basal', 'membrana basal', 'estratificado', 'queratina', 'layers'],
    render: props => <Layers size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'grid_epithelium',
    name: 'Células Epiteliales Poliédricas',
    category: 'anatomy',
    topic: 'epitelios',
    keywords: ['epitelio', 'celulas', 'celula', 'poliedrico', 'mosaico', 'revestimiento', 'simple', 'cubico', 'cilindrico', 'pavimentoso'],
    render: props => <Grid size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'shield',
    name: 'Barrera Epitelial / Uniones Ocluyentes',
    category: 'physiology',
    topic: 'epitelios',
    keywords: ['epitelio', 'barrera', 'proteccion', 'escudo', 'zonula occludens', 'desmosoma', 'hemidesmosoma', 'oclusion', 'uniones'],
    render: props => <ShieldCheck size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'epitelio_brick',
    name: 'Epitelio Plano Estratificado',
    category: 'anatomy',
    topic: 'epitelios',
    keywords: ['epitelio', 'estratificado', 'pared', 'ladrillos', 'epidermis', 'esofago', 'proteccion mecanica', 'brick'],
    render: props => <GiBrickWall size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'epitelio_corneo',
    name: 'Estrato Córneo / Queratinizado',
    category: 'anatomy',
    topic: 'epitelios',
    keywords: ['epitelio', 'queratina', 'corneo', 'córneo', 'estrato corneo', 'armadura', 'escamas', 'piel gruesa'],
    render: props => <GiLayeredArmor size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'epitelio_hex',
    name: 'Malla Epitelial Hexagonal',
    category: 'anatomy',
    topic: 'epitelios',
    keywords: ['epitelio', 'hexagono', 'celulas cubicas', 'endotelio', 'mesotelio', 'hexagonal', 'pavimentoso simple'],
    render: props => <GiHexagonalNut size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'epitelio_reticular',
    name: 'Citoesqueleto y Red Epitelial',
    category: 'physiology',
    topic: 'epitelios',
    keywords: ['epitelio', 'red', 'tonofilamentos', 'queratina', 'complejo de union', 'reticulo', 'filamentos intermedios'],
    render: props => <TbGridPattern size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'epitelio_border',
    name: 'Membrana Basal y Dominios Celulares',
    category: 'physiology',
    topic: 'epitelios',
    keywords: ['epitelio', 'membrana basal', 'polaridad', 'dominio apical', 'dominio basolateral', 'lamina lucida', 'lamina densa'],
    render: props => <TbBorderAll size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'cilia',
    name: 'Cilios / Aclaramiento Mucociliar',
    category: 'physiology',
    topic: 'epitelios',
    keywords: ['epitelio', 'cilios', 'movimiento', 'barrido', 'flujo', 'mucociliar', 'axonema', 'microtubulos', 'pseudoestratificado ciliado'],
    render: props => <Wind size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'absorption',
    name: 'Microvellosidades / Ribete en Cepillo',
    category: 'physiology',
    topic: 'epitelios',
    keywords: ['epitelio', 'microvellosidad', 'microvellosidades', 'ribete en cepillo', 'absorcion', 'enterocito', 'filamentos de actina', 'chapa estriada'],
    render: props => <Download size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // 2. 🧪 GLÁNDULAS ENDOCRINAS Y EXOCRINAS (10 íconos)
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 'droplets',
    name: 'Secreción Exocrina / Acinos',
    category: 'physiology',
    topic: 'glandulas',
    keywords: ['glandula', 'glándula', 'glandulas', 'secrecion', 'exocrina', 'seroso', 'mucoso', 'merocrino', 'acino', 'adenomero'],
    render: props => <Droplets size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'glandula_endocrine',
    name: 'Glándula Endocrina / Vía Sanguínea',
    category: 'physiology',
    topic: 'glandulas',
    keywords: ['glandula', 'glándula', 'endocrina', 'hormona', 'hormonas', 'capilares fenestrados', 'cordones celulares', 'tiroides', 'hipofisis'],
    render: props => <Activity size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'glandula_follicle',
    name: 'Folículo Tiroideo / Coloide',
    category: 'anatomy',
    topic: 'glandulas',
    keywords: ['glandula', 'glándula', 'tiroides', 'tirocito', 'coloide', 'tiroglobulina', 't3', 't4', 'foliculo tiroideo'],
    render: props => <Crosshair size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'glandula_flask',
    name: 'Síntesis y Vesículas Secretoras',
    category: 'lab',
    topic: 'glandulas',
    keywords: ['glandula', 'glándula', 'secrecion', 'vesicula', 'golgi', 'reticulo endoplasmico', 'granulos de cimogeno'],
    render: props => <GiWaterFlask size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'glandula_mucus',
    name: 'Célula Caliciforme / Moco Protector',
    category: 'anatomy',
    topic: 'glandulas',
    keywords: ['glandula', 'glándula', 'caliciforme', 'mucina', 'moco', 'pas positivo', 'glandula unicelular', 'estomago'],
    render: props => <GiMucousPillar size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'glandula_droplet_half',
    name: 'Secreción Mixta (Seromucosa)',
    category: 'physiology',
    topic: 'glandulas',
    keywords: ['glandula', 'glándula', 'mixta', 'semiluna de giannuzzi', 'submandibular', 'seromucoso', 'acino mixto'],
    render: props => <TbDropletHalf2 size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'glandula_holocrine',
    name: 'Glándula Holocrina / Sebácea',
    category: 'physiology',
    topic: 'glandulas',
    keywords: ['glandula', 'glándula', 'holocrina', 'sebacea', 'sebo', 'apoptosis secretora', 'foliculo piloso'],
    render: props => <GiOilySpiral size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'glandula_adrenal',
    name: 'Glándula Suprarrenal (Corteza y Médula)',
    category: 'anatomy',
    topic: 'glandulas',
    keywords: ['glandula', 'glándula', 'suprarrenal', 'adrenal', 'cortisol', 'aldosterona', 'glomerular', 'fascicular', 'reticular', 'medula'],
    render: props => <Layers size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'glandula_receptors',
    name: 'Receptores Hormonales Tisulares',
    category: 'physiology',
    topic: 'glandulas',
    keywords: ['glandula', 'glándula', 'receptores', 'hormonas', 'transduccion', 'celula diana', 'feedback'],
    render: props => <Target size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'glandula_merocrine',
    name: 'Secreción Merocrina / Ecrina',
    category: 'physiology',
    topic: 'glandulas',
    keywords: ['glandula', 'glándula', 'merocrina', 'ecrina', 'sudoripara', 'exocitosis', 'sin perdida celular'],
    render: props => <GiDroplets size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // 3. 🔬 MICROSCOPIOS (10 íconos)
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 'microscope',
    name: 'Microscopio Óptico Compuesto',
    category: 'lab',
    topic: 'microscopios',
    keywords: ['microscopio', 'microscopios', 'microscopia', 'optico', 'campo claro', 'fotomicroscopio', 'laboratorio', 'microscope'],
    render: props => <Microscope size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'microscope_lens',
    name: 'Revólver & Objetivos (4x - 100x)',
    category: 'lab',
    topic: 'microscopios',
    keywords: ['microscopio', 'objetivo', 'lente', 'revolver', '4x', '10x', '40x', '100x', 'apertura numerica'],
    render: props => <GiMicroscopeLens size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'microscope_lab',
    name: 'Microscopio Electrónico / Contraste',
    category: 'lab',
    topic: 'microscopios',
    keywords: ['microscopio', 'microscopia electronica', 'tem', 'sem', 'barrido', 'transmision', 'ultraestructura'],
    render: props => <GiMicroscope size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'microscope_tb',
    name: 'Microscopio de Investigación Médica',
    category: 'lab',
    topic: 'microscopios',
    keywords: ['microscopio', 'investigacion', 'platina mecanica', 'condensador de abbe', 'diafragma iris'],
    render: props => <TbMicroscope size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'scan',
    name: 'Escaneo de Placa / Fotomicrografía',
    category: 'lab',
    topic: 'microscopios',
    keywords: ['microscopio', 'escaneo', 'digital', 'fotomicrografia', 'wsi', 'slide scanner', 'resolucion'],
    render: props => <Scan size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'crosshair_target',
    name: 'Retícula Óptica y Micrométrica',
    category: 'lab',
    topic: 'microscopios',
    keywords: ['microscopio', 'reticula', 'micrometro ocular', 'medicion celulas', 'calibracion', 'crosshair'],
    render: props => <Crosshair size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'search',
    name: 'Exploración de la Muestra (Scanning)',
    category: 'lab',
    topic: 'microscopios',
    keywords: ['microscopio', 'exploracion', 'barrido panoramico', 'busqueda', 'campo visual', 'search'],
    render: props => <Search size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'zoom_in',
    name: 'Inmersión en Aceite (100x)',
    category: 'lab',
    topic: 'microscopios',
    keywords: ['microscopio', 'inmersion', 'aceite de cedro', 'gran aumento', '100x', 'indice de refraccion'],
    render: props => <TbZoomIn size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'safety_glasses',
    name: 'Seguridad en el Laboratorio',
    category: 'lab',
    topic: 'microscopios',
    keywords: ['microscopio', 'seguridad', 'proteccion ocular', 'lentes', 'laboratorio', 'bioseguridad', 'gafas'],
    render: props => <GiProtectionGlasses size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'pipette',
    name: 'Montaje de Muestras y Bálsamo',
    category: 'lab',
    topic: 'microscopios',
    keywords: ['microscopio', 'pipeta', 'gotero', 'balsamo de canada', 'cubreobjetos', 'portaobjetos', 'montaje'],
    render: props => <Pipette size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // 4. 🧈 TEJIDO ADIPOSO (8 íconos)
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 'adiposo_paniculo',
    name: 'Tejido Adiposo / Panículo Adiposo',
    category: 'anatomy',
    topic: 'adiposo',
    keywords: ['adiposo', 'tejido adiposo', 'grasa', 'grasa blanca', 'adipocito', 'adipocitos', 'hipodermis', 'aislante', 'fat'],
    render: props => <GiFat size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'adiposo_spiral',
    name: 'Gota Lipídica Coalescente',
    category: 'physiology',
    topic: 'adiposo',
    keywords: ['adiposo', 'lipido', 'trigliceridos', 'gota lipidica', 'inclusion', 'sudan', 'reserva energetica'],
    render: props => <GiOilySpiral size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'adiposo_meat',
    name: 'Tejido Conectivo y Grasa Interlobulillar',
    category: 'anatomy',
    topic: 'adiposo',
    keywords: ['adiposo', 'grasa', 'lobulillo', 'estroma', 'adiposa', 'intersticial', 'marmoleado'],
    render: props => <GiMeat size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'droplet_single',
    name: 'Adipocito Unilocular / Anillo de Sello',
    category: 'anatomy',
    topic: 'adiposo',
    keywords: ['adiposo', 'adipocito', 'unilocular', 'anillo de sello', 'nucleo aplanado', 'vacuola', 'grasa blanca'],
    render: props => <Droplet size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'droplet_fa',
    name: 'Gotícula Lipídica / Esterificación',
    category: 'physiology',
    topic: 'adiposo',
    keywords: ['adiposo', 'acido graso', 'lipolisis', 'lipogenesis', 'triglicerido', 'adipocinas', 'leptina'],
    render: props => <FaDroplet size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'adiposo_ring',
    name: 'Morfología en Anillo de Sello',
    category: 'anatomy',
    topic: 'adiposo',
    keywords: ['adiposo', 'anillo de sello', 'vacuola lipidica', 'croma', 'preparacion histologica', 'espacio opticamente vacio'],
    render: props => <TbDropletHalf2 size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'adiposo_brown',
    name: 'Grasa Parda / Termogénesis (UCP-1)',
    category: 'physiology',
    topic: 'adiposo',
    keywords: ['adiposo', 'grasa parda', 'multilocular', 'termogenesis', 'mitocondrias', 'termogenina', 'calor', 'ucp1'],
    render: props => <Sun size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'weight_scale',
    name: 'Metabolismo Energético Adiposo',
    category: 'clinical',
    topic: 'adiposo',
    keywords: ['adiposo', 'metabolismo', 'peso', 'insulina', 'obesidad', 'grasa visceral', 'almacen'],
    render: props => <FaWeightScale size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // 5. 🦴 HUESO (9 íconos)
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 'bone',
    name: 'Hueso Cortical / Matriz Ósea',
    category: 'anatomy',
    topic: 'hueso',
    keywords: ['hueso', 'huesos', 'oseo', 'óseo', 'osteocito', 'osteoblasto', 'osteoclasto', 'havers', 'compacto', 'matriz calcificada', 'bone'],
    render: props => <FaBone size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'skeleton',
    name: 'Sistema Óseo / Esqueleto Trabecular',
    category: 'anatomy',
    topic: 'hueso',
    keywords: ['hueso', 'huesos', 'esqueleto', 'locomotor', 'trabeculas', 'esponjoso', 'skeleton'],
    render: props => <GiSkeleton size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'hueso_compacto',
    name: 'Osteonas y Laminillas Óseas',
    category: 'anatomy',
    topic: 'hueso',
    keywords: ['hueso', 'huesos', 'osteona', 'laminillas', 'conducto de havers', 'conducto de volkmann', 'canaliculos', 'osteocito'],
    render: props => <GiBoneKnife size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'skull_bone',
    name: 'Osificación Intramembranosa',
    category: 'anatomy',
    topic: 'hueso',
    keywords: ['hueso', 'huesos', 'craneo', 'intramembranosa', 'hueso plano', 'fontanela', 'sutura', 'periostio', 'osteoblastos'],
    render: props => <GiSkullCrossedBones size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'ribcage',
    name: 'Hueso Esponjoso & Médula Ósea',
    category: 'anatomy',
    topic: 'hueso',
    keywords: ['hueso', 'huesos', 'medula osea', 'hematopoyesis', 'trabecular', 'costillas', 'esternon', 'endostio'],
    render: props => <GiRibcage size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'spine',
    name: 'Vértebra / Conducto Raquídeo',
    category: 'anatomy',
    topic: 'hueso',
    keywords: ['hueso', 'huesos', 'vertebra', 'columna', 'medula', 'hueso esponjoso', 'eje axial', 'spine'],
    render: props => <GiSpineArrow size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'hueso_tb',
    name: 'Matriz Osteoide y Mineralización',
    category: 'physiology',
    topic: 'hueso',
    keywords: ['hueso', 'huesos', 'hidroxiapatita', 'calcio', 'fosfato', 'colageno tipo i', 'remodelado', 'osteona'],
    render: props => <TbBone size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'hueso_filled',
    name: 'Periostio y Fibras de Sharpey',
    category: 'anatomy',
    topic: 'hueso',
    keywords: ['hueso', 'huesos', 'periostio', 'fibras de sharpey', 'matriz osea densa', 'cortical osea'],
    render: props => <TbBoneFilled size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'hueso_resorption',
    name: 'Osteoclastos / Lagunas de Howship',
    category: 'physiology',
    topic: 'hueso',
    keywords: ['hueso', 'osteoclasto', 'lagunas de howship', 'borde en cepillo', 'resorcion osea', 'remodelado oseo'],
    render: props => <GiBoneKnife size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // 6. 🦻 CARTÍLAGO (9 íconos)
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 'joint',
    name: 'Articulación / Cartílago Hialino Articular',
    category: 'anatomy',
    topic: 'cartilago',
    keywords: ['cartilago', 'cartílago', 'cartilagos', 'articulacion', 'hialino', 'sinovial', 'condrocito', 'condroplasto', 'grupos isogenos', 'joint'],
    render: props => <GiJoint size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'cartilago_nasal',
    name: 'Cartílago Hialino Nasal',
    category: 'anatomy',
    topic: 'cartilago',
    keywords: ['cartilago', 'cartílago', 'nasal', 'tabique', 'hialino', 'aleteo', 'pericondrio', 'matriz territorial'],
    render: props => <GiNoseFront size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'ear',
    name: 'Cartílago Elástico / Pabellón Auricular',
    category: 'anatomy',
    topic: 'cartilago',
    keywords: ['cartilago', 'cartílago', 'elastico', 'oreja', 'pabellon', 'epiglotis', 'fibras elasticas', 'resorcina', 'orceina'],
    render: props => <FaEarListen size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'cartilago_human_ear',
    name: 'Condrocitos Elásticos y Matriz Auricular',
    category: 'anatomy',
    topic: 'cartilago',
    keywords: ['cartilago', 'cartílago', 'elastico', 'condrocito', 'matriz elastica', 'conducto auditivo externo', 'trompa de eustaquio'],
    render: props => <GiHumanEar size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'cartilago_fibro',
    name: 'Fibrocartílago / Meniscos y Discos',
    category: 'anatomy',
    topic: 'cartilago',
    keywords: ['cartilago', 'cartílago', 'fibrocartilago', 'disco intervertebral', 'menisco', 'sinfisis pubica', 'colageno tipo i', 'resistencia'],
    render: props => <GiArmBandage size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'cartilago_matrix',
    name: 'Matriz Cartilaginosa Avascular',
    category: 'physiology',
    topic: 'cartilago',
    keywords: ['cartilago', 'cartílago', 'matriz', 'condroitin sulfato', 'agrecan', 'avascular', 'difusion', 'pericondrio', 'condroblasto'],
    render: props => <TbBoneOff size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'shield_outline',
    name: 'Pericondrio / Capa Condrogénica',
    category: 'physiology',
    topic: 'cartilago',
    keywords: ['cartilago', 'cartílago', 'pericondrio', 'capa fibrosa', 'capa celular', 'crecimiento por aposicion', 'crecimiento intersticial'],
    render: props => <Shield size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'cartilago_broken',
    name: 'Reparación y Regeneración Condral',
    category: 'clinical',
    topic: 'cartilago',
    keywords: ['cartilago', 'cartílago', 'condrogenesis', 'lesion condral', 'matriz interterritorial', 'artrosis'],
    render: props => <GiBrokenBone size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'cartilago_leg',
    name: 'Placa Epifisaria / Cartílago de Crecimiento',
    category: 'anatomy',
    topic: 'cartilago',
    keywords: ['cartilago', 'cartílago', 'disco epifisario', 'zona de proliferacion', 'zona de hipertrofia', 'osificacion endocondral'],
    render: props => <GiLeg size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // 7. 🧠 SISTEMA NERVIOSO (9 íconos)
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 'brain',
    name: 'Cerebro / Encéfalo y Sustancia Gris',
    category: 'anatomy',
    topic: 'nervioso',
    keywords: ['nervioso', 'nervio', 'cerebro', 'neurona', 'corteza', 'sinapsis', 'astrocito', 'glia', 'pericarion', 'brain'],
    render: props => <FaBrain size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'nervioso_cortex',
    name: 'Corteza Cerebral y Neuronas Piramidales',
    category: 'anatomy',
    topic: 'nervioso',
    keywords: ['nervioso', 'corteza', 'piramidal', 'betz', 'molecular', 'granular', 'capas corticales', 'cerebelo', 'purkinje'],
    render: props => <GiBrain size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'zap',
    name: 'Potencial de Acción / Impulso Nervioso',
    category: 'physiology',
    topic: 'nervioso',
    keywords: ['nervioso', 'potencial de accion', 'despolarizacion', 'impulso', 'axon', 'conduccion saltatoria', 'nodo de ranvier'],
    render: props => <Zap size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'network',
    name: 'Red Neuronal / Neuropilo Tisular',
    category: 'physiology',
    topic: 'nervioso',
    keywords: ['nervioso', 'red', 'neuropilo', 'dendritas', 'sinapsis', 'astrocitos protoplasmaticos', 'oligodendrocitos'],
    render: props => <Network size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'cpu_metabolism',
    name: 'Soma Neuronal / Corpúsculos de Nissl',
    category: 'physiology',
    topic: 'nervioso',
    keywords: ['nervioso', 'soma', 'pericarion', 'sustancia de nissl', 'reticulo endoplasmico', 'cono axonico', 'nucleolo prominente'],
    render: props => <Cpu size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'share_synapse',
    name: 'Sinapsis Química / Neurotransmisores',
    category: 'physiology',
    topic: 'nervioso',
    keywords: ['nervioso', 'sinapsis', 'hendidura sinaptica', 'vesiculas sinapticas', 'neurotransmisor', 'acetilcolina', 'recetores'],
    render: props => <Share2 size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'nervioso_tb_brain',
    name: 'Médula Espinal / Astas Anteriores y Posteriores',
    category: 'anatomy',
    topic: 'nervioso',
    keywords: ['nervioso', 'medula espinal', 'astas', 'motoneurona', 'conducto ependimario', 'ependimocitos', 'mielina'],
    render: props => <TbBrain size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'nervioso_tb_network',
    name: 'Células Gliales / Microglía y Schwann',
    category: 'anatomy',
    topic: 'nervioso',
    keywords: ['nervioso', 'glia', 'microglia', 'fagocitosis', 'celulas de schwann', 'vaina de mielina', 'nervio periferico'],
    render: props => <TbNetwork size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'nervioso_periphery',
    name: 'Nervio Periférico (Epineuro, Perineuro, Endoneuro)',
    category: 'anatomy',
    topic: 'nervioso',
    keywords: ['nervioso', 'nervio periferico', 'epineuro', 'perineuro', 'endoneuro', 'fasciculo nervioso', 'axones mielinicos'],
    render: props => <Layers size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // 8. 🩸 SANGRE (9 íconos)
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 'blood',
    name: 'Frotis Sanguíneo / Eritrocitos & Leucocitos',
    category: 'anatomy',
    topic: 'sangre',
    keywords: ['sangre', 'eritrocito', 'globulo rojo', 'leucocito', 'plaqueta', 'frotis', 'hematologia', 'wright', 'blood'],
    render: props => <GiBlood size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'sangre_heart_drop',
    name: 'Vaso Sanguíneo y Perfusión',
    category: 'physiology',
    topic: 'sangre',
    keywords: ['sangre', 'lecho vascular', 'perfusion', 'flujo sanguineo', 'plasma', 'hematocrito'],
    render: props => <GiHeartDrop size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'sangre_drop',
    name: 'Gota de Sangre / Tinción Hematológica',
    category: 'lab',
    topic: 'sangre',
    keywords: ['sangre', 'gota', 'frotis', 'giemsa', 'leishman', 'plaquetas', 'trombocito'],
    render: props => <FaDroplet size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'vial_single',
    name: 'Tubo de Extracción / Plasma y Suero',
    category: 'lab',
    topic: 'sangre',
    keywords: ['sangre', 'vial', 'tubo', 'anticoagulante', 'edta', 'centrifugacion', 'plasma', 'suero'],
    render: props => <FaVial size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'syringe',
    name: 'Extracción / Punción Capilar y Venosa',
    category: 'clinical',
    topic: 'sangre',
    keywords: ['sangre', 'jeringa', 'puncion', 'flebotomia', 'muestra', 'hematologia'],
    render: props => <FaSyringe size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'sangre_rbc',
    name: 'Eritrocito Disco Bicóncavo',
    category: 'anatomy',
    topic: 'sangre',
    keywords: ['sangre', 'eritrocito', 'biconcavo', 'hemoglobina', 'espectrina', 'anucleado', 'reticulocito'],
    render: props => <TbDropletFilled size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'sangre_capilar',
    name: 'Microhematocrito y Elementos Formes',
    category: 'lab',
    topic: 'sangre',
    keywords: ['sangre', 'hematocrito', 'neutrofilo', 'eosinofilo', 'basofilo', 'linfocito', 'monocito'],
    render: props => <TbTestPipe size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'heart_pulse',
    name: 'Circulación Sanguínea / Diapedesis',
    category: 'physiology',
    topic: 'sangre',
    keywords: ['sangre', 'circulacion', 'diapedesis', 'migracion leucocitaria', 'hemostasia', 'coagulacion'],
    render: props => <FaHeartPulse size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'sangre_splash',
    name: 'Cascada de la Coagulación / Fibrina',
    category: 'physiology',
    topic: 'sangre',
    keywords: ['sangre', 'coagulacion', 'fibrina', 'trombina', 'tapón plaquetario', 'hemostasia primaria', 'hemostasia secundaria'],
    render: props => <GiDropletSplash size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // 9. 🛡️ SISTEMA LINFOIDE E INMUNIDAD (10 íconos)
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 'shield_check_lymph',
    name: 'Sistema Inmune / Linfocitos T y B',
    category: 'physiology',
    topic: 'linfoide',
    keywords: ['linfoide', 'inmunidad', 'linfocito t', 'linfocito b', 'cd4', 'cd8', 'celulas plasmaticas', 'inmunocompetencia'],
    render: props => <ShieldCheck size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'shield_alert',
    name: 'Respuesta Inmune e Inflamación',
    category: 'physiology',
    topic: 'linfoide',
    keywords: ['linfoide', 'inflamacion', 'citoquinas', 'quimiotaxis', 'histamina', 'mastocito', 'celulas cebadas'],
    render: props => <ShieldAlert size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'shield_heart',
    name: 'Inmunocompetencia / Timo y Bazo',
    category: 'anatomy',
    topic: 'linfoide',
    keywords: ['linfoide', 'timo', 'bazo', 'corpusculos de hassall', 'seleccion positiva', 'seleccion negativa', 'organo linfoide'],
    render: props => <FaShieldHeart size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'linfoide_barrier',
    name: 'Barrera Inmune / MALT & Placas de Peyer',
    category: 'anatomy',
    topic: 'linfoide',
    keywords: ['linfoide', 'malt', 'placas de peyer', 'amigdalas', 'foliculos linfoides', 'centros germinativos'],
    render: props => <FaShieldVirus size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'virus',
    name: 'Antígeno Patógeno / Opsonización',
    category: 'physiology',
    topic: 'linfoide',
    keywords: ['linfoide', 'antigeno', 'patogeno', 'virus', 'opsonizacion', 'inmunoglobulina igg', 'complemento'],
    render: props => <FaVirus size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'bacteria',
    name: 'Macrófagos / Células Presentadoras (APC)',
    category: 'physiology',
    topic: 'linfoide',
    keywords: ['linfoide', 'macrofago', 'celula dendritica', 'apc', 'cph ii', 'fagocitosis', 'lisosomas'],
    render: props => <FaBacteria size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'internal_organ',
    name: 'Bazo / Pulpa Blanca y Pulpa Roja',
    category: 'anatomy',
    topic: 'linfoide',
    keywords: ['linfoide', 'bazo', 'pulpa blanca', 'pulpa roja', 'cordones de billroth', 'sinusoides esplenicos', 'hemocateresis'],
    render: props => <GiInternalOrgan size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'linfoide_crosshair',
    name: 'Plasmocitos e Inmunoglobulinas',
    category: 'physiology',
    topic: 'linfoide',
    keywords: ['linfoide', 'plasmocito', 'anticuerpo', 'inmunoglobulina', 'nucleo en rueda de carreta', 'iga secretora'],
    render: props => <Crosshair size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'virus_covid',
    name: 'Microbiología e Infección',
    category: 'lab',
    topic: 'linfoide',
    keywords: ['linfoide', 'microbiologia', 'virus', 'infeccion', 'diagnostico'],
    render: props => <FaVirusCovid size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'linfoide_node',
    name: 'Ganglio Linfático / Senos Subcapsulares',
    category: 'anatomy',
    topic: 'linfoide',
    keywords: ['linfoide', 'ganglio linfatico', 'corteza ganglionar', 'paracorteza', 'vasos linfaticos aferentes', 'linfa'],
    render: props => <GiOrganigram size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // 10. 💪 MÚSCULO (9 íconos)
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 'muscle',
    name: 'Músculo Esquelético / Estriado',
    category: 'anatomy',
    topic: 'musculo',
    keywords: ['musculo', 'músculo', 'musculos', 'muscular', 'esqueletico', 'estriado', 'sarcomero', 'miofibrilla', 'muscle'],
    render: props => <GiMuscleUp size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'musculo_biceps',
    name: 'Vientre Muscular y Envolturas (Epimisio)',
    category: 'anatomy',
    topic: 'musculo',
    keywords: ['musculo', 'músculo', 'epimisio', 'perimisio', 'endomisio', 'fasciculo muscular', 'biceps'],
    render: props => <GiBiceps size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'musculo_fiber',
    name: 'Miofibrillas y Bandas Sarcoméricas',
    category: 'physiology',
    topic: 'musculo',
    keywords: ['musculo', 'músculo', 'banda a', 'banda i', 'linea z', 'zona h', 'sarcomero', 'actina', 'miosina', 'estriaciones'],
    render: props => <GiMuscleFat size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'musculo_lucide_biceps',
    name: 'Contracción Muscular Activa',
    category: 'physiology',
    topic: 'musculo',
    keywords: ['musculo', 'músculo', 'contraccion', 'calcio', 'reticulo sarcoplasmico', 'tubulos t', 'puentes cruzados'],
    render: props => <BicepsFlexed size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'activity',
    name: 'Músculo Cardíaco / Discos Intercalares',
    category: 'anatomy',
    topic: 'musculo',
    keywords: ['musculo', 'músculo', 'cardiaco', 'miocardio', 'discos intercalares', 'desmosomas', 'uniones gap', 'nucleo central'],
    render: props => <Activity size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'waves',
    name: 'Músculo Liso / Células Fusiformes',
    category: 'anatomy',
    topic: 'musculo',
    keywords: ['musculo', 'músculo', 'liso', 'fusiforme', 'cuerpos densos', 'calmodulina', 'involuntario', 'peristaltismo'],
    render: props => <Waves size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'musculo_dumbbell',
    name: 'Tono Muscular y Fibras Tipo I/II',
    category: 'clinical',
    topic: 'musculo',
    keywords: ['musculo', 'músculo', 'fibras rojas', 'fibras blancas', 'mioglobina', 'hipertrofia', 'resistencia'],
    render: props => <FaDumbbell size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'musculo_arm',
    name: 'Placa Neuromotora / Unión Neuromuscular',
    category: 'physiology',
    topic: 'musculo',
    keywords: ['musculo', 'músculo', 'placa motora', 'union neuromuscular', 'acetilcolina', 'hendidura sinaptica', 'terminacion motora'],
    render: props => <GiArm size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'musculo_sprint',
    name: 'Metabolismo Anaeróbico y Glucógeno Muscular',
    category: 'physiology',
    topic: 'musculo',
    keywords: ['musculo', 'músculo', 'glucogeno', 'lactato', 'fosfocreatina', 'fatiga muscular', 'sprint'],
    render: props => <GiSprint size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // 11. 🫀 SISTEMA CARDIOVASCULAR (9 íconos)
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 'heart_organ',
    name: 'Corazón / Endocardio, Miocardio y Epicardio',
    category: 'anatomy',
    topic: 'cardiovascular',
    keywords: ['cardiovascular', 'corazon', 'corazón', 'miocardio', 'endocardio', 'epicardio', 'pericardio', 'auriculas', 'ventriculos'],
    render: props => <GiHeartOrgan size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'heart_simple',
    name: 'Arterias y Venas / Túnica Íntima y Media',
    category: 'anatomy',
    topic: 'cardiovascular',
    keywords: ['cardiovascular', 'arteria', 'vena', 'tunica intima', 'tunica media', 'tunica adventicia', 'vasa vasorum', 'elastica interna'],
    render: props => <FaHeart size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'heart_lucide',
    name: 'Bomba Cardíaca / Fibras de Purkinje',
    category: 'physiology',
    topic: 'cardiovascular',
    keywords: ['cardiovascular', 'purkinje', 'sistema de conduccion', 'nodo sinusal', 'nodo av', 'haz de his'],
    render: props => <Heart size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'cardio_pulse',
    name: 'Pulso Arterial / Fibras Elásticas',
    category: 'physiology',
    topic: 'cardiovascular',
    keywords: ['cardiovascular', 'pulso', 'arteria elastica', 'aorta', 'presion arterial', 'efecto windkessel'],
    render: props => <FaHeartPulse size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'stethoscope',
    name: 'Hemodinámica y Ruidos Cardíacos',
    category: 'clinical',
    topic: 'cardiovascular',
    keywords: ['cardiovascular', 'estetoscopio', 'valvulas cardiacas', 'auscultacion', 'ruidos cardiacos', 'flujo laminar'],
    render: props => <FaStethoscope size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'cardio_monitor',
    name: 'Endotelio Vascular / Óxido Nítrico',
    category: 'physiology',
    topic: 'cardiovascular',
    keywords: ['cardiovascular', 'endotelio', 'celulas endoteliales', 'oxido nitrico', 'vasodilatacion', 'permeabilidad vascular'],
    render: props => <TbDeviceHeartMonitor size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'exchange',
    name: 'Capilares Continuos, Fenestrados y Sinusoides',
    category: 'physiology',
    topic: 'cardiovascular',
    keywords: ['cardiovascular', 'capilares', 'intercambio de gases', 'difusion capilar', 'fenestraciones', 'sinusoides', 'pericitos'],
    render: props => <ArrowRightLeft size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'cardio_heartbeat',
    name: 'Válvulas Cardíacas / Cuerdas Tendinosas',
    category: 'anatomy',
    topic: 'cardiovascular',
    keywords: ['cardiovascular', 'valvulas', 'valvula mitral', 'valvula tricuspide', 'cuerdas tendinosas', 'musculos papilares'],
    render: props => <TbActivityHeartbeat size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'cardio_shield',
    name: 'Presión Hidrostática y Retorno Venoso',
    category: 'physiology',
    topic: 'cardiovascular',
    keywords: ['cardiovascular', 'volemia', 'presion venosa', 'valvulas venosas', 'presion oncotica'],
    render: props => <FaShieldHeart size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // 12. 👆 SISTEMA TEGUMENTARIO (PIEL) (9 íconos)
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 'fingerprint',
    name: 'Crestas Epidérmicas / Dermatoglifos',
    category: 'anatomy',
    topic: 'tegumentario',
    keywords: ['tegumentario', 'piel', 'dermis', 'epidermis', 'crestas dermicas', 'huella dactilar', 'papilas dermicas', 'dermatoglifos'],
    render: props => <Fingerprint size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'tegumentario_dermis',
    name: 'Dermis Papilar y Reticular',
    category: 'anatomy',
    topic: 'tegumentario',
    keywords: ['tegumentario', 'piel', 'dermis papilar', 'dermis reticular', 'colageno tipo i', 'fibras elasticas', 'fibroblastos'],
    render: props => <GiFingerPrint size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'tegumentario_layers',
    name: 'Estratos Epidérmicos (Basal a Córneo)',
    category: 'anatomy',
    topic: 'tegumentario',
    keywords: ['tegumentario', 'piel', 'estrato basal', 'estrato espinoso', 'estrato granuloso', 'estrato lucido', 'estrato corneo'],
    render: props => <Layers size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'tegumentario_melanocyte',
    name: 'Melanocitos / Síntesis de Melanina',
    category: 'physiology',
    topic: 'tegumentario',
    keywords: ['tegumentario', 'piel', 'melanocito', 'melanosoma', 'melanina', 'proteccion uv', 'tirosinasa', 'estrato basal'],
    render: props => <Sun size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'hand_holding_medical',
    name: 'Sensibilidad Cutánea y Receptores',
    category: 'clinical',
    topic: 'tegumentario',
    keywords: ['tegumentario', 'piel', 'receptores sensoriales', 'tacto', 'temperatura', 'dolor', 'terminaciones libres'],
    render: props => <FaHandHoldingMedical size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'tegumentario_receptor',
    name: 'Corpúsculos de Meissner y Pacini',
    category: 'anatomy',
    topic: 'tegumentario',
    keywords: ['tegumentario', 'piel', 'meissner', 'pacini', 'rufini', 'krause', 'mecanorreceptores', 'presion y vibracion'],
    render: props => <TbFingerprint size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'tegumentario_keratin',
    name: 'Queratinocitos y Gránulos de Queratohialina',
    category: 'physiology',
    topic: 'tegumentario',
    keywords: ['tegumentario', 'piel', 'queratinocito', 'queratohialina', 'filagrina', 'tonofilamentos', 'queratinizacion'],
    render: props => <ShieldCheck size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'tegumentario_wound',
    name: 'Reepitelización y Cicatrización Cutánea',
    category: 'clinical',
    topic: 'tegumentario',
    keywords: ['tegumentario', 'piel', 'cicatrizacion', 'tejido de granulacion', 'reepitelizacion', 'miofibroblastos', 'herida'],
    render: props => <GiOpenWound size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'tegumentario_armor',
    name: 'Barrera Cutánea e Hidratación',
    category: 'physiology',
    topic: 'tegumentario',
    keywords: ['tegumentario', 'piel', 'barrera cutanea', 'ceramidas', 'manto lipidico', 'perdida transepidermica de agua'],
    render: props => <GiLayeredArmor size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // 13. 🫁 SISTEMA RESPIRATORIO (9 íconos)
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 'lungs',
    name: 'Pulmones / Árbol Traqueobronquial',
    category: 'anatomy',
    topic: 'respiratorio',
    keywords: ['respiratorio', 'pulmon', 'pulmones', 'pulmón', 'traquea', 'tráquea', 'bronquios', 'bronquiolos', 'arbol bronquial', 'lungs'],
    render: props => <FaLungs size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'lungs_virus',
    name: 'Parénquima Pulmonar y Tabiques Alveolares',
    category: 'anatomy',
    topic: 'respiratorio',
    keywords: ['respiratorio', 'pulmon', 'pulmones', 'parenquima', 'intersticio alveolar', 'tabiques', 'macrofagos alveolares'],
    render: props => <FaLungsVirus size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'respiratorio_sacs',
    name: 'Alvéolos y Neumocitos I y II',
    category: 'anatomy',
    topic: 'respiratorio',
    keywords: ['respiratorio', 'alveolo', 'alvéolo', 'alveolos', 'neumocitos tipo i', 'neumocitos tipo ii', 'surfactante pulmonar', 'dipalmitoilfosfatidilcolina'],
    render: props => <GiLungs size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'respiratorio_wind',
    name: 'Epitelio Respiratorio Ciliado',
    category: 'physiology',
    topic: 'respiratorio',
    keywords: ['respiratorio', 'epitelio pseudoestratificado ciliado', 'celulas caliciformes', 'aclaramiento mucociliar', 'traquea', 'tráquea'],
    render: props => <Wind size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'nose',
    name: 'Cavidad Nasal y Mucosa Olfatoria',
    category: 'anatomy',
    topic: 'respiratorio',
    keywords: ['respiratorio', 'nariz', 'cavidad nasal', 'mucosa olfatoria', 'neuronas bipolares', 'celulas basales', 'glandulas de bowman'],
    render: props => <GiNoseFront size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'respiratorio_tb_lungs',
    name: 'Barrera Hematogaseosa / Hematosis',
    category: 'physiology',
    topic: 'respiratorio',
    keywords: ['respiratorio', 'hematosis', 'barrera alveolocapilar', 'oxigeno', 'oxígeno', 'co2', 'difusion de gases', 'pulmon'],
    render: props => <TbLungs size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'respiratorio_airflow',
    name: 'Ventilación Pulmonar / Flujo Aéreo',
    category: 'physiology',
    topic: 'respiratorio',
    keywords: ['respiratorio', 'ventilacion', 'flujo aereo', 'inspiracion', 'espiracion', 'volumen corriente'],
    render: props => <GiCrossedAirFlows size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'respiratorio_zigzag',
    name: 'Anillos Traqueales y Músculo Traqueal',
    category: 'anatomy',
    topic: 'respiratorio',
    keywords: ['respiratorio', 'traquea', 'tráquea', 'cartilago traqueal', 'anillos en c', 'musculo traquealis'],
    render: props => <GiAirZigzag size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'respiratorio_windslap',
    name: 'Tensión Superficial y Surfactante Alveolar',
    category: 'physiology',
    topic: 'respiratorio',
    keywords: ['respiratorio', 'tension superficial', 'cuerpos lamelares', 'colapso alveolar', 'atelectasia'],
    render: props => <GiWindSlap size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // 14. 🥣 SISTEMA DIGESTIVO (9 íconos)
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 'stomach',
    name: 'Estómago / Células Parietales y Principales',
    category: 'anatomy',
    topic: 'digestivo',
    keywords: ['digestivo', 'estomago', 'estómago', 'mucosa gastrica', 'foveolas', 'celulas parietales', 'acido clorhidrico', 'factor intrinseco', 'pepsinogeno'],
    render: props => <GiStomach size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'digestivo_motility',
    name: 'Motilidad y Plexos Entéricos (Auerbach)',
    category: 'physiology',
    topic: 'digestivo',
    keywords: ['digestivo', 'peristalsis', 'plexo mienterico', 'auerbach', 'meissner', 'muscular externa', 'capas circulares y longitudinales'],
    render: props => <Waves size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'digestivo_absorb',
    name: 'Vellosidades Intestinales / Enterocitos',
    category: 'physiology',
    topic: 'digestivo',
    keywords: ['digestivo', 'intestino delgado', 'duodeno', 'yeyuno', 'ileon', 'íleon', 'vellosidades', 'quilifero central', 'absorcion de nutrientes'],
    render: props => <Download size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'digestivo_apple',
    name: 'Tubo Digestivo y Tránsito Quimo/Quilo',
    category: 'physiology',
    topic: 'digestivo',
    keywords: ['digestivo', 'digestion', 'digestión', 'quimo', 'quilo', 'esofago', 'esófago', 'colon', 'absorcion de agua'],
    render: props => <TbApple size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'digestivo_acid',
    name: 'Secreción Ácida y Enzimas Digestivas',
    category: 'physiology',
    topic: 'digestivo',
    keywords: ['digestivo', 'acido gastrico', 'bomba de protones', 'jugo gastrico', 'quimica digestiva', 'ph gastrico'],
    render: props => <GiBubblingFlask size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'digestivo_crypts',
    name: 'Criptas de Lieberkühn & Células de Paneth',
    category: 'anatomy',
    topic: 'digestivo',
    keywords: ['digestivo', 'criptas de lieberkuhn', 'paneth', 'lisozima', 'colonocitos', 'tenias del colon', 'glandulas intestinales'],
    render: props => <GiCellarBarrels size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'digestivo_bowels',
    name: 'Intestino Grueso / Colon y Apéndice',
    category: 'anatomy',
    topic: 'digestivo',
    keywords: ['digestivo', 'colon', 'intestino grueso', 'ciego', 'apendice', 'recto', 'haustras', 'microbiota intestinal'],
    render: props => <GiBowels size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'digestivo_eating',
    name: 'Deglución y Peristaltismo Esofágico',
    category: 'physiology',
    topic: 'digestivo',
    keywords: ['digestivo', 'esofago', 'esófago', 'deglucion', 'esfinter esofagico', 'peristaltismo primario y secundario'],
    render: props => <GiEating size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'digestivo_mucous',
    name: 'Barrera Mucosa Gástrica e Intestinal',
    category: 'anatomy',
    topic: 'digestivo',
    keywords: ['digestivo', 'mucosa gastrica', 'bicarbonato', 'celulas mucosas del cuello', 'proteccion gastrica'],
    render: props => <GiMucousPillar size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // 15. 👄 CAVIDAD ORAL (9 íconos)
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 'tooth',
    name: 'Diente / Odontoblastos, Dentina y Esmalte',
    category: 'anatomy',
    topic: 'oral',
    keywords: ['oral', 'diente', 'dientes', 'esmalte', 'ameloblastos', 'dentina', 'odontoblastos', 'pulpa', 'cemento', 'ligamento periodontal'],
    render: props => <FaTooth size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'oral_tooth_gi',
    name: 'Corona Dental y Periodonto',
    category: 'anatomy',
    topic: 'oral',
    keywords: ['oral', 'diente', 'dientes', 'corona dental', 'raiz', 'alveolo dentario', 'periodonto', 'odontogenesis'],
    render: props => <GiTooth size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'oral_tongue',
    name: 'Lengua y Papilas Linguales',
    category: 'anatomy',
    topic: 'oral',
    keywords: ['oral', 'lengua', 'papila filiforme', 'papila fungiforme', 'papila caliciforme', 'papila foliada', 'musculo lingual'],
    render: props => <GiTongue size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'mouth',
    name: 'Mucosa Oral y Secreción Salival',
    category: 'anatomy',
    topic: 'oral',
    keywords: ['oral', 'boca', 'mucosa masticatoria', 'mucosa de revestimiento', 'paladar', 'encias', 'saliva', 'amilasa'],
    render: props => <GiMouthWatering size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'oral_dental_tb',
    name: 'Pulpa Dental y Plexo de Raschkow',
    category: 'anatomy',
    topic: 'oral',
    keywords: ['oral', 'pulpa', 'conducto radicular', 'inervacion dental', 'tejido conectivo laxo de la pulpa'],
    render: props => <TbDental size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'oral_taste',
    name: 'Botones Gustativos y Corpúsculos',
    category: 'physiology',
    topic: 'oral',
    keywords: ['oral', 'boton gustativo', 'poro gustativo', 'receptores del gusto', 'salado', 'dulce', 'amargo', 'acido', 'umami'],
    render: props => <Sparkles size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'oral_lipstick',
    name: 'Labios y Zona de Transición Mucocutánea',
    category: 'anatomy',
    topic: 'oral',
    keywords: ['oral', 'labio', 'labios', 'bermellon', 'zona de transicion', 'epitelio queratinizado y no queratinizado'],
    render: props => <GiLipstick size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'oral_saliva_drop',
    name: 'Glándulas Salivales Menores (Labiales y Linguales)',
    category: 'anatomy',
    topic: 'oral',
    keywords: ['oral', 'glandulas salivales menores', 'glandulas de von ebner', 'lipasa lingual', 'mucosa bucal'],
    render: props => <GiChemicalDrop size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'oral_ameloblast',
    name: 'Prismas del Esmalte y Amelogénesis',
    category: 'physiology',
    topic: 'oral',
    keywords: ['oral', 'esmalte dental', 'prismas de esmalte', 'estrias de retzius', 'ameloblasto', 'calcificacion dental'],
    render: props => <Crosshair size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // 16. 🧫 GLÁNDULAS ANEXAS DEL SISTEMA DIGESTIVO (9 íconos)
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 'liver',
    name: 'Hígado / Lobulillo Clásico y Hepatocitos',
    category: 'anatomy',
    topic: 'anexas',
    keywords: ['anexas', 'higado', 'hígado', 'lobulillo hepatico', 'triada portal', 'hepatocito', 'sinusoide', 'celulas de kupffer', 'espacio de disse'],
    render: props => <GiLiver size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'anexas_pancreas',
    name: 'Páncreas / Acinos e Islotes de Langerhans',
    category: 'anatomy',
    topic: 'anexas',
    keywords: ['anexas', 'pancreas', 'páncreas', 'acinos serosos', 'celulas centroacinares', 'islotes de langerhans', 'insulina', 'glucagon', 'somatostatina'],
    render: props => <GiInternalOrgan size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'anexas_bile',
    name: 'Conductillos Biliares y Secreción de Bilis',
    category: 'physiology',
    topic: 'anexas',
    keywords: ['anexas', 'bilis', 'canaliculos biliares', 'sales biliares', 'bilirrubina', 'conducto hepatico', 'coledoco'],
    render: props => <GiChemicalDrop size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'anexas_vesicle',
    name: 'Vesícula Biliar / Concentración y Mucosa',
    category: 'anatomy',
    topic: 'anexas',
    keywords: ['anexas', 'vesicula biliar', 'vesícula', 'mucosa plegada', 'senos de rokitansky-aschoff', 'colecistoquinina', 'concentracion biliar'],
    render: props => <GiWaterFlask size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'anexas_salivary',
    name: 'Glándulas Salivales Mayores (Parótida, etc.)',
    category: 'anatomy',
    topic: 'anexas',
    keywords: ['anexas', 'parotida', 'parótida', 'submandibular', 'sublingual', 'acinos serosos puros', 'semilunas de serous giannuzzi', 'salival'],
    render: props => <Droplets size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'anexas_target',
    name: 'Células Diana de Insulina y Glucagón',
    category: 'physiology',
    topic: 'anexas',
    keywords: ['anexas', 'receptores', 'insulina', 'glucogenogenesis', 'glucogenolisis', 'homeostasis glucosa'],
    render: props => <Target size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'anexas_droplets',
    name: 'Jugo Pancreático Exocrino y Bicarbonato',
    category: 'physiology',
    topic: 'anexas',
    keywords: ['anexas', 'pancreas exocrino', 'tripsina', 'quimotripsina', 'amilasa pancreatica', 'lipasa', 'conducto de wirsung'],
    render: props => <GiDroplets size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'anexas_ito',
    name: 'Células Estrelladas Hepáticas (Células de Ito)',
    category: 'anatomy',
    topic: 'anexas',
    keywords: ['anexas', 'higado', 'celulas de ito', 'vitamina a', 'fibrogenesis hepatica', 'espacio perisinusoidal'],
    render: props => <Star size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'anexas_triad',
    name: 'Tríada Portal (Vena, Arteria y Conductillo)',
    category: 'anatomy',
    topic: 'anexas',
    keywords: ['anexas', 'higado', 'triada portal', 'espacio porta de kiernan', 'vena porta', 'arteria hepatica', 'conducto biliar'],
    render: props => <Grid size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // 17. 💧 SISTEMA URINARIO (9 íconos)
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 'kidneys',
    name: 'Riñones / Nefrona y Corpúsculo Renal',
    category: 'anatomy',
    topic: 'urinario',
    keywords: ['urinario', 'riñon', 'rinon', 'riñón', 'riñones', 'rinones', 'renal', 'nefrona', 'corteza renal', 'medula renal', 'piramides de malpighi', 'kidney'],
    render: props => <GiKidneys size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'filter',
    name: 'Filtración Glomerular / Podocitos y Pedicelos',
    category: 'physiology',
    topic: 'urinario',
    keywords: ['urinario', 'riñon', 'rinon', 'glomerulo', 'glomérulo', 'podocitos', 'ranura de filtracion', 'pedicelos', 'capsula de bowman', 'mesangio'],
    render: props => <Filter size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'funnel',
    name: 'Túbulos Contorneados y Colectores',
    category: 'anatomy',
    topic: 'urinario',
    keywords: ['urinario', 'riñon', 'rinon', 'tubulo contorneado proximal', 'asa de henle', 'tubulo distal', 'tubulo colector', 'caliz renal', 'pelvis renal'],
    render: props => <GiFunnel size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'urinario_urine',
    name: 'Ultrafiltrado Urinario / Excreción',
    category: 'physiology',
    topic: 'urinario',
    keywords: ['urinario', 'orina', 'ultrafiltrado', 'aclaramiento', 'reabsorcion de agua', 'aldosterona', 'adh', 'vejiga'],
    render: props => <FaDroplet size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'urinario_urothelium',
    name: 'Urotelio / Epitelio de Transición',
    category: 'anatomy',
    topic: 'urinario',
    keywords: ['urinario', 'urotelio', 'epitelio de transicion', 'celulas en paraguas', 'placas uroplaquicas', 'vejiga', 'ureter', 'uréter'],
    render: props => <ShieldCheck size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'urinario_reabsorption',
    name: 'Reabsorción Tubular / Mecanismo Contracorriente',
    category: 'physiology',
    topic: 'urinario',
    keywords: ['urinario', 'mecanismo contracorriente', 'vasos rectos', 'intersticio medular hiperosmotico', 'transporte tubular', 'acuaporinas'],
    render: props => <ArrowRightLeft size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'urinario_splash',
    name: 'Aparato Yuxtaglomerular y Renina',
    category: 'physiology',
    topic: 'urinario',
    keywords: ['urinario', 'aparato yuxtaglomerular', 'macula densa', 'celulas yuxtaglomerulares', 'renina', 'sistema renina angiotensina'],
    render: props => <GiDropletSplash size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'urinario_drop',
    name: 'Presión de Filtración Neta Glomerular',
    category: 'physiology',
    topic: 'urinario',
    keywords: ['urinario', 'presion hidrostatica glomerular', 'tasa de filtrado glomerular', 'tfg', 'depuracion de creatinina'],
    render: props => <GiWaterDrop size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'urinario_bottle',
    name: 'Concentración Urinaria y Sedimento Renal',
    category: 'lab',
    topic: 'urinario',
    keywords: ['urinario', 'sedimento urinario', 'cilindros hialinos', 'densidad urinaria', 'osmolaridad'],
    render: props => <FaBottleDroplet size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // 18. 🧬 SISTEMA REPRODUCTOR (MASCULINO Y FEMENINO) (10 íconos)
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 'reproductor_male',
    name: 'Aparato Reproductor Masculino / Testículo',
    category: 'anatomy',
    topic: 'reproductor',
    keywords: ['reproductor', 'masculino', 'testiculo', 'testículo', 'espermatogenesis', 'tubulos seminiferos', 'sertoli', 'leydig', 'testosterona'],
    render: props => <FaMars size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'reproductor_female',
    name: 'Aparato Reproductor Femenino / Ovario',
    category: 'anatomy',
    topic: 'reproductor',
    keywords: ['reproductor', 'femenino', 'ovario', 'foliculos', 'trompas de falopio', 'utero', 'útero', 'endometrio', 'cuerpo luteo'],
    render: props => <FaVenus size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'reproductor_venus_mars',
    name: 'Fecundación y Gametogénesis',
    category: 'physiology',
    topic: 'reproductor',
    keywords: ['reproductor', 'gametogenesis', 'meiosis', 'fecundacion', 'espermatozoide', 'ovocito', 'cigoto'],
    render: props => <FaVenusMars size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'reproductor_testis',
    name: 'Túbulos Seminíferos y Espermiogénesis',
    category: 'anatomy',
    topic: 'reproductor',
    keywords: ['reproductor', 'epididimo', 'estereocilios', 'conducto deferente', 'prostata', 'próstata', 'vesiculas seminales', 'esperma'],
    render: props => <TbGenderMale size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'reproductor_ovary',
    name: 'Folículos Ováricos (Primordial a Graaf)',
    category: 'anatomy',
    topic: 'reproductor',
    keywords: ['reproductor', 'foliculo de graaf', 'antro folicular', 'zona pelucida', 'corona radiata', 'teca interna', 'estrogenos'],
    render: props => <TbGenderFemale size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'reproductor_fetus',
    name: 'Desarrollo Embrionario e Implantación',
    category: 'anatomy',
    topic: 'reproductor',
    keywords: ['reproductor', 'embrion', 'embrión', 'feto', 'blastocisto', 'trofoblasto', 'placenta', 'vellosidades corionicas', 'implantacion'],
    render: props => <GiFetus size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'reproductor_uterus',
    name: 'Endometrio Uterino / Fase Proliferativa y Secretora',
    category: 'anatomy',
    topic: 'reproductor',
    keywords: ['reproductor', 'utero', 'útero', 'endometrio', 'miometrio', 'glandulas endometriales', 'decidua', 'embarazo', 'ciclo menstrual'],
    render: props => <FaPersonPregnant size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'reproductor_egg_pod',
    name: 'Folículo Maduro y Ovulación',
    category: 'physiology',
    topic: 'reproductor',
    keywords: ['reproductor', 'ovulacion', 'cuerpo albicans', 'cuerpo luteo', 'progesterona', 'foliculo roto'],
    render: props => <GiEggPod size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'reproductor_oocyte',
    name: 'Ovocito Secundario y Zona Pelúcida',
    category: 'anatomy',
    topic: 'reproductor',
    keywords: ['reproductor', 'ovocito', 'ovulo', 'óvulo', 'zona pelucida', 'reaccion acrosomica', 'polocito'],
    render: props => <GiRawEgg size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'dna',
    name: 'Genética Reproductiva y Meiosis',
    category: 'lab',
    topic: 'reproductor',
    keywords: ['reproductor', 'adn', 'cromosomas', 'recombinacion genetica', 'meiosis i', 'meiosis ii', 'haploide'],
    render: props => <GiDna1 size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // 19. 🍼 GLÁNDULA MAMARIA (9 íconos)
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 'mamaria_lactating',
    name: 'Glándula Mamaria Activa / Lactancia',
    category: 'anatomy',
    topic: 'mamaria',
    keywords: ['mamaria', 'glandula mamaria', 'glándula mamaria', 'mama', 'mamas', 'lactancia', 'alveolos mamarios', 'conductos galactoforos', 'oxitocina', 'prolactina'],
    render: props => <FaPersonBreastfeeding size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'mamaria_bottle',
    name: 'Conductos Galactóforos y Seno Lactífero',
    category: 'anatomy',
    topic: 'mamaria',
    keywords: ['mamaria', 'seno lactifero', 'conducto galactoforo', 'pezon', 'pezón', 'areola', 'secrecion lactea', 'leche materna'],
    render: props => <GiBabyBottle size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'mamaria_alveoli',
    name: 'Alvéolos Mamarios y Células Mioepiteliales',
    category: 'physiology',
    topic: 'mamaria',
    keywords: ['mamaria', 'alveolo mamario', 'alvéolos', 'celulas mioepiteliales', 'contraccion', 'eyeccion lactea', 'lobulillo mamario'],
    render: props => <TbBabyBottle size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'mamaria_milk',
    name: 'Secreción Apocrina (Lípidos) y Merocrina (Caseína)',
    category: 'physiology',
    topic: 'mamaria',
    keywords: ['mamaria', 'leche', 'caseina', 'globulo de grasa de la leche', 'secrecion apocrina', 'secrecion merocrina', 'colostro'],
    render: props => <TbMilk size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'child',
    name: 'Reflejo de Succión y Síntesis Láctea',
    category: 'clinical',
    topic: 'mamaria',
    keywords: ['mamaria', 'lactante', 'succion', 'arco reflejo neuroendocrino', 'hipotalamo', 'pecho'],
    render: props => <FaBaby size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'mamaria_secretion',
    name: 'Estroma Intralobulillar e Interlobulillar',
    category: 'anatomy',
    topic: 'mamaria',
    keywords: ['mamaria', 'estroma intralobulillar', 'estroma interlobulillar', 'tejido adiposo mamario', 'suspensorios de cooper'],
    render: props => <Droplets size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'mamaria_chest',
    name: 'Pared Torácica y Ligamentos de Cooper',
    category: 'anatomy',
    topic: 'mamaria',
    keywords: ['mamaria', 'ligamentos de cooper', 'fascia pectoral', 'arquitectura mamaria', 'lobulos mamarios'],
    render: props => <GiChestArmor size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'mamaria_carton',
    name: 'Composición y Nutrientes de la Leche Materna',
    category: 'physiology',
    topic: 'mamaria',
    keywords: ['mamaria', 'leche humana', 'inmunoglobulina iga secretora', 'lactosa', 'nutricion neonatal'],
    render: props => <GiMilkCarton size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'mamaria_carriage',
    name: 'Glándula Mamaria en Reposo vs Gestacional',
    category: 'clinical',
    topic: 'mamaria',
    keywords: ['mamaria', 'reposo mamario', 'cambios gestacionales', 'lobulillos secretores', 'involucion mamaria'],
    render: props => <FaBabyCarriage size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // 20. 👁️ OJO Y SENTIDOS ESPECIALES (10 íconos)
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 'eye',
    name: 'Globo Ocular / Túnica Fibrosa, Vascular y Nerviosa',
    category: 'anatomy',
    topic: 'ojo',
    keywords: ['ojo', 'ojos', 'ocular', 'globo ocular', 'esclera', 'coroides', 'retina', 'vision', 'visión', 'eye'],
    render: props => <Eye size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'eye_lucide',
    name: 'Medios Refringentes / Cristalino y Humor Vítreo',
    category: 'anatomy',
    topic: 'ojo',
    keywords: ['ojo', 'ojos', 'cristalino', 'humor vitreo', 'humor acuoso', 'camara anterior', 'camara posterior', 'refraccion'],
    render: props => <FaEye size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'eyeball',
    name: 'Retina / 10 Capas y Fotorreceptores',
    category: 'anatomy',
    topic: 'ojo',
    keywords: ['ojo', 'ojos', 'retina', 'bastones', 'conos', 'epitelio pigmentario de la retina', 'celulas ganglionares', 'plexiforme'],
    render: props => <GiEyeball size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'ojo_iris',
    name: 'Iris / Estroma Pigmentado y Cuerpo Ciliar',
    category: 'anatomy',
    topic: 'ojo',
    keywords: ['ojo', 'ojos', 'iris', 'estroma pigmentado', 'cuerpo ciliar', 'procesos ciliares', 'humor acuoso', 'melanocitos oculares'],
    render: props => <GiShinyIris size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'ojo_pupil',
    name: 'Pupila / Esfínter y Dilatador Pupilar',
    category: 'physiology',
    topic: 'ojo',
    keywords: ['ojo', 'ojos', 'pupila', 'esfinter pupilar', 'dilatador pupilar', 'miosis', 'midriasis', 'reflejo fotomotor'],
    render: props => <GiStarPupil size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'ojo_cornea',
    name: 'Córnea / Epitelio Anterior y Endotelio',
    category: 'anatomy',
    topic: 'ojo',
    keywords: ['ojo', 'ojos', 'cornea', 'córnea', 'epitelio corneal', 'membrana de bowman', 'estroma corneal', 'membrana de descemet', 'endotelio corneal'],
    render: props => <GiMazeCornea size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'ojo_fovea',
    name: 'Fóvea Central y Agudeza Visual',
    category: 'physiology',
    topic: 'ojo',
    keywords: ['ojo', 'ojos', 'fovea', 'fóvea', 'macula lutea', 'agudeza visual', 'conos foveales', 'vision central'],
    render: props => <Crosshair size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'ojo_focus',
    name: 'Acomodación Cristaliniana / Zónula de Zinn',
    category: 'physiology',
    topic: 'ojo',
    keywords: ['ojo', 'ojos', 'cristalino', 'zonula de zinn', 'musculo ciliar', 'acomodacion', 'enfoque'],
    render: props => <Target size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'ojo_allseeing',
    name: 'Visión Fotópica y Escotópica (Bastones y Conos)',
    category: 'physiology',
    topic: 'ojo',
    keywords: ['ojo', 'ojos', 'vision nocturna', 'rodopsina', 'fotopigmentos', 'sensibilidad a la luz', 'fototransduccion'],
    render: props => <GiAllSeeingEye size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'ojo_vision',
    name: 'Agudeza Visual y Vía Óptica',
    category: 'clinical',
    topic: 'ojo',
    keywords: ['ojo', 'ojos', 'nervio optico', 'quiasma optico', 'campo visual', 'agudeza visual', 'oftalmologia'],
    render: props => <FaEyeLowVision size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // 21. 🩺 OTROS / DIAGNÓSTICO Y TINCIONES (11 íconos)
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: 'palette',
    name: 'Coloración y Tinciones Histológicas',
    category: 'lab',
    topic: 'otros',
    keywords: ['coloracion', 'tincion', 'h&e', 'hematoxilina', 'eosina', 'pas', 'tricromico', 'palette'],
    render: props => <Palette size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'atom',
    name: 'Biología Celular y Molecular',
    category: 'lab',
    topic: 'otros',
    keywords: ['celula', 'celular', 'organelo', 'mitocondria', 'nucleo', 'citoplasma', 'biologia'],
    render: props => <Atom size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'dna2',
    name: 'Ácido Desoxirribonucleico (ADN)',
    category: 'lab',
    topic: 'otros',
    keywords: ['adn', 'nucleo', 'cromatina', 'eucromatina', 'heterocromatina', 'genetica'],
    render: props => <GiDna2 size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'hospital',
    name: 'Hospital / Servicio de Patología',
    category: 'clinical',
    topic: 'otros',
    keywords: ['hospital', 'clinica', 'patologia', 'biopsia', 'diagnostico'],
    render: props => <FaHospital size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'caduceus',
    name: 'Símbolo Médico / Vara de Esculapio',
    category: 'clinical',
    topic: 'otros',
    keywords: ['medicina', 'simbolo', 'salud', 'asclepio', 'caduceo'],
    render: props => <FaStaffSnake size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'notes_medical',
    name: 'Informe Histopatológico',
    category: 'clinical',
    topic: 'otros',
    keywords: ['informe', 'historia clinica', 'biopsia', 'diagnostico histologico'],
    render: props => <FaNotesMedical size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'badge_check',
    name: 'Criterio Verificado / Control de Calidad',
    category: 'clinical',
    topic: 'otros',
    keywords: ['verificado', 'aprobado', 'diagnostico certero', 'control de calidad', 'check'],
    render: props => <BadgeCheck size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'star',
    name: 'Elemento Clave / Diagnóstico Diferencial',
    category: 'clinical',
    topic: 'otros',
    keywords: ['estrella', 'clave', 'importante', 'patognomonico', 'destacado'],
    render: props => <Star size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'lightbulb',
    name: 'Tip Histológico / Correlación Clínica',
    category: 'clinical',
    topic: 'otros',
    keywords: ['idea', 'tip', 'clave', 'nemotecnia', 'recordar', 'foco'],
    render: props => <Lightbulb size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'map_pin',
    name: 'Localización Histológica / Marcador',
    category: 'clinical',
    topic: 'otros',
    keywords: ['marcador', 'localizacion', 'puntero', 'senalamiento', 'ubicacion'],
    render: props => <MapPin size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'sparkles',
    name: 'Especialización Tisular / Diferenciación',
    category: 'physiology',
    topic: 'otros',
    keywords: ['especializacion', 'destacado', 'diferenciacion', 'maduracion', 'brillo', 'sparkles'],
    render: props => <Sparkles size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
];

export const ICONS_BY_ID = new Map<string, MedicalIconDefinition>(
  MEDICAL_ICONS_CATALOG.map(item => [item.id, item])
);
