import React from 'react';
import {
  Microscope,
  FlaskConical,
  FlaskRound,
  TestTube,
  TestTube2,
  ShieldCheck,
  ShieldAlert,
  Shield,
  ArrowRightLeft,
  Filter,
  Sparkles,
  Droplets,
  Droplet,
  Layers,
  Wind,
  Waves,
  Zap,
  Activity,
  Scan,
  Palette,
  Pipette,
  MapPin,
  BadgeCheck,
  CheckCircle2,
  AlertCircle,
  Star,
  Info,
  Download,
  Flame,
  Sun,
  Target,
  Crosshair,
  Grid,
  Network,
  Cpu,
  Fingerprint,
  Gauge,
  Lightbulb,
  Search,
  Share2,
  Sliders,
  Wand2,
  Atom,
  Heart,
  Eye,
  BookOpen,
} from 'lucide-react';
import {
  FaLungs,
  FaLungsVirus,
  FaBrain,
  FaBone,
  FaDna,
  FaBacteria,
  FaVirus,
  FaVirusCovid,
  FaSyringe,
  FaCapsules,
  FaPills,
  FaStethoscope,
  FaHeartPulse,
  FaHeart,
  FaHospital,
  FaEye,
  FaEarListen,
  FaTooth,
  FaTemperatureHalf,
  FaWeightScale,
  FaDroplet,
  FaVial,
  FaVials,
  FaMortarPestle,
  FaPrescriptionBottleMedical,
  FaShieldHeart,
  FaHandHoldingMedical,
  FaNotesMedical,
  FaFileMedical,
  FaStaffSnake,
  FaBookMedical,
  FaPerson,
  FaChild,
  FaPersonWalking,
} from 'react-icons/fa6';
import {
  GiKidneys,
  GiStomach,
  GiLiver,
  GiHeartOrgan,
  GiMuscleUp,
  GiSpineArrow,
  GiBlood,
  GiChemicalDrop,
  GiFunnel,
  GiMolecule,
  GiInternalOrgan,
  GiRibcage,
  GiSkullCrossedBones,
  GiSkeleton,
  GiJoint,
  GiArmBandage,
  GiEyeball,
  GiNoseFront,
  GiMouthWatering,
  GiGears,
  GiHealthCapsule,
  GiMicroscopeLens,
  GiTestTubes,
  GiDrippingTube,
  GiDna2,
  GiChemicalTank,
  GiProtectionGlasses,
} from 'react-icons/gi';

export interface MedicalIconDefinition {
  id: string;
  name: string;
  category: 'anatomy' | 'physiology' | 'lab' | 'clinical';
  keywords: string[];
  render: (props: { size?: number; className?: string; style?: React.CSSProperties; color?: string }) => React.ReactElement;
}

export const MEDICAL_ICONS_CATALOG: MedicalIconDefinition[] = [
  // ── 🫀 ÓRGANOS, TEJIDOS & ANATOMÍA ──────────────────────────────────
  {
    id: 'kidneys',
    name: 'Riñón / Sistema Renal',
    category: 'anatomy',
    keywords: ['riñon', 'riñones', 'renal', 'nefrona', 'bowman', 'tubulo', 'corteza renal', 'medula', 'kidney'],
    render: props => <GiKidneys size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'lungs',
    name: 'Pulmón / Respiratorio',
    category: 'anatomy',
    keywords: ['pulmon', 'pulmones', 'respiratorio', 'alveolo', 'bronquio', 'neumocito', 'aire', 'pleura', 'lung'],
    render: props => <FaLungs size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'lungs_virus',
    name: 'Pulmón Afectado / Inflamación',
    category: 'anatomy',
    keywords: ['neumonia', 'pulmon', 'infeccion', 'alveolo', 'edema', 'respiratorio'],
    render: props => <FaLungsVirus size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'heart_organ',
    name: 'Corazón (Órgano Anatómico)',
    category: 'anatomy',
    keywords: ['corazon', 'cardiaco', 'miocardio', 'endocardio', 'ventriculo', 'auricula', 'heart', 'organ'],
    render: props => <GiHeartOrgan size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'heart_simple',
    name: 'Corazón / Circulación Sanguínea',
    category: 'anatomy',
    keywords: ['corazon', 'cardiaco', 'vasos', 'arteria', 'vena', 'circulacion', 'heart'],
    render: props => <FaHeart size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'heart_lucide',
    name: 'Corazón Esquemático / Miocardio',
    category: 'anatomy',
    keywords: ['corazon', 'miocardiocito', 'auricula', 'ventriculo', 'valvula', 'heart'],
    render: props => <Heart size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'stomach',
    name: 'Estómago / Mucosa Gástrica',
    category: 'anatomy',
    keywords: ['estomago', 'gastrico', 'digestivo', 'mucosa', 'foveola', 'acida', 'pepsina', 'stomach'],
    render: props => <GiStomach size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'liver',
    name: 'Hígado / Lobulillo Hepático',
    category: 'anatomy',
    keywords: ['higado', 'hepatico', 'hepatocito', 'lobulillo', 'sinusoide', 'biliar', 'kupffer', 'liver'],
    render: props => <GiLiver size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'internal_organ',
    name: 'Víscera / Órgano Macizo',
    category: 'anatomy',
    keywords: ['viscera', 'organo', 'parenquima', 'estroma', 'bazo', 'pancreas', 'organ'],
    render: props => <GiInternalOrgan size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'brain',
    name: 'Cerebro / Sistema Nervioso',
    category: 'anatomy',
    keywords: ['cerebro', 'neurona', 'nervioso', 'encefalo', 'corteza', 'sinapsis', 'astrocito', 'glia', 'brain'],
    render: props => <FaBrain size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'spine',
    name: 'Columna / Médula Espinal',
    category: 'anatomy',
    keywords: ['columna', 'medula', 'vertebra', 'espinal', 'eje', 'sustancia gris', 'sustancia blanca', 'spine'],
    render: props => <GiSpineArrow size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'bone',
    name: 'Hueso / Matriz Ósea',
    category: 'anatomy',
    keywords: ['hueso', 'oseo', 'osteocito', 'osteoblasto', 'havers', 'esqueleto', 'compacto', 'esponjoso', 'bone'],
    render: props => <FaBone size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'skeleton',
    name: 'Esqueleto / Sistema Óseo',
    category: 'anatomy',
    keywords: ['esqueleto', 'huesos', 'locomotor', 'cuerpo', 'calavera', 'skeleton'],
    render: props => <GiSkeleton size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'skull_bone',
    name: 'Cráneo / Suturas Óseas',
    category: 'anatomy',
    keywords: ['craneo', 'cabeza', 'hueso plano', 'sutura', 'meninges', 'calavera'],
    render: props => <GiSkullCrossedBones size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'ribcage',
    name: 'Caja Torácica / Costillas',
    category: 'anatomy',
    keywords: ['torax', 'costillas', 'cartilago costal', 'pleura', 'esternon', 'ribcage'],
    render: props => <GiRibcage size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'joint',
    name: 'Articulación / Cartílago Articular',
    category: 'anatomy',
    keywords: ['articulacion', 'cartilago', 'hialino', 'sinovial', 'condrocito', 'capsula', 'joint'],
    render: props => <GiJoint size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'muscle',
    name: 'Músculo / Miocitos Estriados',
    category: 'anatomy',
    keywords: ['musculo', 'muscular', 'miocito', 'fibra', 'sarcomero', 'estriado', 'esqueletico', 'liso', 'muscle'],
    render: props => <GiMuscleUp size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'eye',
    name: 'Ojo / Globo Ocular',
    category: 'anatomy',
    keywords: ['ojo', 'retina', 'cornea', 'vision', 'ocular', 'cristalino', 'esclera', 'conos', 'bastones', 'eye'],
    render: props => <FaEye size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'eye_lucide',
    name: 'Ojo / Enfoque Esquemático',
    category: 'anatomy',
    keywords: ['ojo', 'vision', 'pupila', 'iris', 'optica', 'eye'],
    render: props => <Eye size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'eyeball',
    name: 'Retina / Epitelio Pigmentario',
    category: 'anatomy',
    keywords: ['retina', 'ojo', 'vision', 'pupila', 'iris', 'ocular', 'eyeball'],
    render: props => <GiEyeball size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'ear',
    name: 'Oído / Cóclea & Órgano de Corti',
    category: 'anatomy',
    keywords: ['oido', 'auditivo', 'coclea', 'timpano', 'oreja', 'vestibulo', 'corti', 'ear'],
    render: props => <FaEarListen size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'nose',
    name: 'Nariz / Mucosa Respiratoria y Olfatoria',
    category: 'anatomy',
    keywords: ['nariz', 'pituitaria', 'olfatorio', 'nasal', 'mucosa olfativa', 'cornetes', 'nose'],
    render: props => <GiNoseFront size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'mouth',
    name: 'Cavidad Oral / Glándulas Salivales',
    category: 'anatomy',
    keywords: ['boca', 'oral', 'lengua', 'papila', 'salival', 'parotida', 'acinos', 'mouth'],
    render: props => <GiMouthWatering size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'tooth',
    name: 'Diente / Odontoblastos & Dentina',
    category: 'anatomy',
    keywords: ['diente', 'dental', 'esmalte', 'dentina', 'pulpa', 'odontoblasto', 'cemento', 'tooth'],
    render: props => <FaTooth size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'blood',
    name: 'Sangre / Frotis Sanguíneo',
    category: 'anatomy',
    keywords: ['sangre', 'eritrocito', 'hematologia', 'leucocito', 'globulo rojo', 'plaqueta', 'vaso', 'blood'],
    render: props => <GiBlood size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'cell',
    name: 'Célula / Estructura Molecular',
    category: 'anatomy',
    keywords: ['celula', 'celular', 'membrana', 'nucleo', 'citoplasma', 'organelo', 'mitocondria', 'cell', 'molecula'],
    render: props => <GiMolecule size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'person',
    name: 'Cuerpo Humano / Sistémico',
    category: 'anatomy',
    keywords: ['cuerpo', 'humano', 'individuo', 'sistemico', 'anatomia', 'person'],
    render: props => <FaPerson size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'child',
    name: 'Embriología / Desarrollo Fetal',
    category: 'anatomy',
    keywords: ['embrion', 'desarrollo', 'pediatrico', 'infantil', 'germinal', 'blastocisto', 'child'],
    render: props => <FaChild size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'person_walking',
    name: 'Aparato Locomotor / Movilidad',
    category: 'anatomy',
    keywords: ['locomocion', 'movimiento', 'marcha', 'musculoesqueletico', 'tendon'],
    render: props => <FaPersonWalking size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },

  // ── ⚡ FISIOLOGÍA & PROCESOS BIOLÓGICOS ─────────────────────────────
  {
    id: 'exchange',
    name: 'Intercambio / Difusión de Gases',
    category: 'physiology',
    keywords: ['intercambio', 'difusion', 'paso', 'gases', 'permeabilidad', 'transporte', 'exchange', 'transfer'],
    render: props => <ArrowRightLeft size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'filter',
    name: 'Filtración Glomerular / Tamiz',
    category: 'physiology',
    keywords: ['filtracion', 'filtro', 'filtrado', 'glomerulo', 'tamiz', 'selectivo', 'podocito', 'filter'],
    render: props => <Filter size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'funnel',
    name: 'Conducción / Drenaje Tubular',
    category: 'physiology',
    keywords: ['embudo', 'conduccion', 'flujo', 'paso', 'drenaje', 'conducto', 'funnel'],
    render: props => <GiFunnel size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'shield',
    name: 'Barrera Epitelial / Protección',
    category: 'physiology',
    keywords: ['barrera', 'proteccion', 'escudo', 'resistencia', 'estratificado', 'oclusion', 'desmosoma', 'shield'],
    render: props => <ShieldCheck size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'shield_alert',
    name: 'Fallo de Barrera / Inflamación',
    category: 'physiology',
    keywords: ['ruptura', 'infiltrado', 'dano', 'lesion', 'inflamacion', 'alerta', 'shield'],
    render: props => <ShieldAlert size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'shield_outline',
    name: 'Inmunidad / Defensas Tisulares',
    category: 'physiology',
    keywords: ['inmune', 'defensa', 'anticuerpo', 'linfocito', 'fagocitosis', 'proteccion'],
    render: props => <Shield size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'shield_heart',
    name: 'Protección Cardiovascular',
    category: 'physiology',
    keywords: ['cardioproteccion', 'endotelio', 'oxigenacion', 'inmunidad'],
    render: props => <FaShieldHeart size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'droplets',
    name: 'Secreción / Glándulas Exocrinas',
    category: 'physiology',
    keywords: ['secrecion', 'liquido', 'seroso', 'mucoso', 'merocrino', 'apocrino', 'holocrino', 'glandula', 'droplets'],
    render: props => <Droplets size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'droplet_single',
    name: 'Gotícula Lipídica / Adipocito',
    category: 'physiology',
    keywords: ['lipido', 'adipocito', 'grasa', 'gota', 'sebo', 'sebaceo', 'droplet'],
    render: props => <Droplet size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'droplet_fa',
    name: 'Secreción Acuosa / Sudor',
    category: 'physiology',
    keywords: ['sudor', 'eccrino', 'secrecion acuosa', 'humedad', 'lagrima'],
    render: props => <FaDroplet size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'absorption',
    name: 'Absorción / Microvellosidades',
    category: 'physiology',
    keywords: ['absorcion', 'microvellosidad', 'ribete en cepillo', 'captacion', 'nutrientes', 'entrada', 'absorption'],
    render: props => <Download size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'zap',
    name: 'Potencial de Acción / Impulso Eléctrico',
    category: 'physiology',
    keywords: ['impulso', 'excitabilidad', 'electrico', 'potencial', 'accion', 'nervio', 'despolarizacion', 'zap'],
    render: props => <Zap size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'activity',
    name: 'Actividad Fisiológica / Ritmo',
    category: 'physiology',
    keywords: ['actividad', 'ritmo', 'fisiologia', 'pulso', 'registro', 'frecuencia', 'contraccion', 'activity'],
    render: props => <Activity size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'layers',
    name: 'Estratificación / Láminas Basales',
    category: 'physiology',
    keywords: ['estrato', 'capas', 'laminas', 'basal', 'membrana basal', 'estratificado', 'queratina', 'layers'],
    render: props => <Layers size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'cilia',
    name: 'Cilios / Aclaramiento Mucociliar',
    category: 'physiology',
    keywords: ['cilios', 'movimiento', 'viento', 'barrido', 'flujo', 'mucociliar', 'axonema', 'wind'],
    render: props => <Wind size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'waves',
    name: 'Peristalsis / Ondas Contráctiles',
    category: 'physiology',
    keywords: ['ondas', 'peristalsis', 'contraccion', 'musculo liso', 'ondulante', 'fluido', 'waves'],
    render: props => <Waves size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'sparkles',
    name: 'Diferenciación / Especialización Tisular',
    category: 'physiology',
    keywords: ['especializacion', 'destacado', 'diferenciacion', 'maduracion', 'brillo', 'sparkles'],
    render: props => <Sparkles size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'wand_special',
    name: 'Transformación / Metaplasia',
    category: 'physiology',
    keywords: ['metaplasia', 'adaptacion', 'cambio', 'transformacion celular', 'magia'],
    render: props => <Wand2 size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'target',
    name: 'Receptor de Membrana / Diana Molecular',
    category: 'physiology',
    keywords: ['receptor', 'diana', 'ligando', 'hormona', 'especificidad', 'senalizacion', 'target'],
    render: props => <Target size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'crosshair_target',
    name: 'Diana Específica / Anticuerpo',
    category: 'physiology',
    keywords: ['antigeno', 'epítopo', 'especifico', 'marcado', 'objetivo', 'crosshair'],
    render: props => <Crosshair size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'network',
    name: 'Uniones Celulares / Redes Tisulares',
    category: 'physiology',
    keywords: ['red', 'uniones', 'gap', 'nexus', 'sinapsis', 'comunicacion', 'intercelular', 'network'],
    render: props => <Network size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'share_synapse',
    name: 'Conexión / Sinapsis Interneuronal',
    category: 'physiology',
    keywords: ['sinapsis', 'conexion', 'red axonal', 'neurotransmisor', 'enlace'],
    render: props => <Share2 size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'gears',
    name: 'Maquinaria Metabólica / Enzimas',
    category: 'physiology',
    keywords: ['metabolismo', 'enzima', 'catalisis', 'sintesis', 'respiracion celular', 'gears'],
    render: props => <GiGears size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'cpu_metabolism',
    name: 'Control Genético / Núcleo Celular',
    category: 'physiology',
    keywords: ['nucleo', 'control', 'transcripcion', 'procesamiento', 'cpu'],
    render: props => <Cpu size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'flame',
    name: 'Termogénesis / Metabolismo Mitocondrial',
    category: 'physiology',
    keywords: ['calor', 'termogenesis', 'grasa parda', 'energia', 'mitocondrias', 'flame'],
    render: props => <Flame size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'sun_metabolism',
    name: 'Ciclo Circadiano / Metabolismo',
    category: 'physiology',
    keywords: ['ciclo', 'ritmo circadiano', 'glandula pineal', 'melatonina', 'luz', 'sol'],
    render: props => <Sun size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'sliders',
    name: 'Homeostasis / Regulación Dinámica',
    category: 'physiology',
    keywords: ['homeostasis', 'regulacion', 'equilibrio', 'ajuste', 'feedback', 'control', 'sliders'],
    render: props => <Sliders size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },

  // ── 🔬 LABORATORIO, MICROSCOPÍA & TINCIONES ────────────────────────
  {
    id: 'microscope',
    name: 'Microscopio Óptico',
    category: 'lab',
    keywords: ['microscopio', 'optico', 'campo claro', 'lupa', 'aumento', 'objetivo', 'ocular', 'microscope'],
    render: props => <Microscope size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'microscope_lens',
    name: 'Lente de Inmersión / Enfoque Fino',
    category: 'lab',
    keywords: ['lente', 'inmersion', '100x', '40x', '10x', 'enfoque', 'micrometrico', 'lens'],
    render: props => <GiMicroscopeLens size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'flask',
    name: 'Matraz Erlenmeyer / Reactivo',
    category: 'lab',
    keywords: ['matraz', 'reactivo', 'solucion', 'quimica', 'tincion', 'preparacion', 'flask'],
    render: props => <FlaskConical size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'flask_round',
    name: 'Matraz de Balón / Solución Tampón',
    category: 'lab',
    keywords: ['matraz', 'balon', 'buffer', 'tampon', 'solucion', 'fijador', 'formol'],
    render: props => <FlaskRound size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'test_tube',
    name: 'Tubo de Ensayo / Muestra',
    category: 'lab',
    keywords: ['tubo', 'ensayo', 'muestra', 'analisis', 'laboratorio', 'vial', 'test tube'],
    render: props => <TestTube size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'test_tube2',
    name: 'Tubo de Ensayo Inclinado / Centrifugación',
    category: 'lab',
    keywords: ['centrifugacion', 'sobrenadante', 'pellet', 'tubo'],
    render: props => <TestTube2 size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'test_tubes_rack',
    name: 'Gradilla de Tubos / Batería de Tinciones',
    category: 'lab',
    keywords: ['tubos', 'bateria', 'alcoholes', 'xilol', 'deshidratacion', 'aclaramiento'],
    render: props => <GiTestTubes size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'vials',
    name: 'Batería de Viales / Anticuerpos',
    category: 'lab',
    keywords: ['vial', 'frascos', 'reactivos', 'anticuerpos', 'inmunohistoquimica', 'vials'],
    render: props => <FaVials size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'vial_single',
    name: 'Vial Individual / Criovial',
    category: 'lab',
    keywords: ['criovial', 'congelacion', 'corte por congelacion', 'muestra'],
    render: props => <FaVial size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'chemical_drop',
    name: 'Gota de Colorante / Tinción H&E',
    category: 'lab',
    keywords: ['colorante', 'tincion', 'gota', 'pigmento', 'eosina', 'hematoxilina', 'coloracion', 'drop'],
    render: props => <GiChemicalDrop size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'dripping_tube',
    name: 'Dispensación de Colorante',
    category: 'lab',
    keywords: ['goteo', 'tincion', 'dispensador', 'hematoxilina', 'colorante', 'reactivo'],
    render: props => <GiDrippingTube size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'palette',
    name: 'Paleta Colorimétrica / Cromatismo',
    category: 'lab',
    keywords: ['paleta', 'color', 'tincion', 'colorimetria', 'tricromico', 'basofilo', 'acidofilo', 'palette'],
    render: props => <Palette size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'pipette',
    name: 'Micropipeta / Alícuota',
    category: 'lab',
    keywords: ['pipeta', 'micropipeta', 'dispensador', 'gota', 'alicuota', 'volumen', 'pipette'],
    render: props => <Pipette size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'scan',
    name: 'Corte / Placa Histológica Escaneada',
    category: 'lab',
    keywords: ['corte', 'placa', 'laminilla', 'cubreobjetos', 'portaobjetos', 'scan', 'wsi', 'preparacion'],
    render: props => <Scan size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'grid_hemocyto',
    name: 'Cámara de Conteo / Cuadrícula',
    category: 'lab',
    keywords: ['neubauer', 'camara', 'conteo', 'cuadricula', 'morfometria', 'grid'],
    render: props => <Grid size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'dna',
    name: 'ADN / Doble Hélice',
    category: 'lab',
    keywords: ['adn', 'cromatina', 'genetica', 'nucleo', 'acido nucleico', 'eucromatina', 'heterocromatina', 'dna'],
    render: props => <FaDna size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'dna2',
    name: 'Genoma / Hibridación In Situ (FISH)',
    category: 'lab',
    keywords: ['gen', 'fish', 'hibridacion', 'sonda', 'cromosoma', 'adn'],
    render: props => <GiDna2 size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'bacteria',
    name: 'Bacteria / Bacilo / Coco',
    category: 'lab',
    keywords: ['bacteria', 'coco', 'bacilo', 'microbio', 'tincion gram', 'ziehl neelsen', 'bacteria'],
    render: props => <FaBacteria size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'virus',
    name: 'Virus / Inclusiones Virales',
    category: 'lab',
    keywords: ['virus', 'capside', 'infeccion', 'patogeno', 'inclusiones', 'cuerpos de inclusion', 'virus'],
    render: props => <FaVirus size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'virus_covid',
    name: 'Coronavirus / Partícula Envuelta',
    category: 'lab',
    keywords: ['covid', 'coronavirus', 'infeccion respiratoria', 'espículas'],
    render: props => <FaVirusCovid size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'mortar_pestle',
    name: 'Mortero / Homogeneización',
    category: 'lab',
    keywords: ['mortero', 'homogeneizado', 'molienda', 'lisis', 'extracto', 'laboratorio'],
    render: props => <FaMortarPestle size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'chemical_tank',
    name: 'Cuba de Tinción / Cubeta Coplin',
    category: 'lab',
    keywords: ['cubeta', 'coplin', 'tincion', 'bateria', 'fijacion', 'formaldehido', 'alcohol'],
    render: props => <GiChemicalTank size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'safety_glasses',
    name: 'Bioseguridad / Lentes de Protección',
    category: 'lab',
    keywords: ['seguridad', 'proteccion', 'lentes', 'gafas', 'bioseguridad', 'quimica'],
    render: props => <GiProtectionGlasses size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'atom',
    name: 'Microscopía Electrónica / Ultraestructura',
    category: 'lab',
    keywords: ['atomo', 'electrones', 'microscopio electronico', 'ultraestructura', 'nanometro', 'tem', 'sem', 'atom'],
    render: props => <Atom size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },

  // ── 🩺 CLÍNICA, DIAGNÓSTICO & PATOLOGÍA ────────────────────────────
  {
    id: 'stethoscope',
    name: 'Estetoscopio / Evaluación Clínica',
    category: 'clinical',
    keywords: ['estetoscopio', 'medico', 'clinica', 'auscultacion', 'doctor', 'correlacion', 'stethoscope'],
    render: props => <FaStethoscope size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'syringe',
    name: 'Jeringa / Biopsia por Aspiración (PAAF)',
    category: 'clinical',
    keywords: ['jeringa', 'inyeccion', 'puncion', 'biopsia', 'paaf', 'aspiracion', 'aguja', 'syringe'],
    render: props => <FaSyringe size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'pill',
    name: 'Cápsula / Farmacología',
    category: 'clinical',
    keywords: ['farmaco', 'medicamento', 'pastilla', 'capsula', 'terapia', 'drogas', 'pill'],
    render: props => <FaCapsules size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'pills',
    name: 'Píldoras / Tratamiento Dirigido',
    category: 'clinical',
    keywords: ['tratamiento', 'pastillas', 'receta', 'farmaco', 'medicacion'],
    render: props => <FaPills size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'health_capsule',
    name: 'Microcápsula / Nanomedicina',
    category: 'clinical',
    keywords: ['capsula', 'nanoparticula', 'liberacion prolongada', 'vehiculo'],
    render: props => <GiHealthCapsule size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'prescription_bottle',
    name: 'Frasco de Muestra en Formol',
    category: 'clinical',
    keywords: ['frasco', 'muestra', 'biopsia', 'formol', 'prescripcion', 'patologia'],
    render: props => <FaPrescriptionBottleMedical size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'thermometer',
    name: 'Termómetro / Síndrome Febril',
    category: 'clinical',
    keywords: ['temperatura', 'termometro', 'fiebre', 'calor', 'signo vital', 'thermometer'],
    render: props => <FaTemperatureHalf size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'weight_scale',
    name: 'Báscula / Peso y Morfometría de Órganos',
    category: 'clinical',
    keywords: ['bascula', 'peso', 'organo', 'gramos', 'morfometria', 'scale'],
    render: props => <FaWeightScale size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'heart_pulse',
    name: 'Pulso Cardíaco / Electrocardiograma',
    category: 'clinical',
    keywords: ['pulso', 'cardiaco', 'electro', 'ecg', 'latido', 'arritmia', 'heart pulse'],
    render: props => <FaHeartPulse size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'hospital',
    name: 'Hospital / Servicio de Patología',
    category: 'clinical',
    keywords: ['hospital', 'clinica', 'centro', 'sanatorio', 'salud', 'servicio de anatomia patologica', 'hospital'],
    render: props => <FaHospital size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'caduceus',
    name: 'Vara de Esculapio / Medicina',
    category: 'clinical',
    keywords: ['medicina', 'esculapio', 'salud', 'medico', 'juramento', 'serpiente', 'caduceus'],
    render: props => <FaStaffSnake size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'notes_medical',
    name: 'Historia Clínica / Informe de Biopsia',
    category: 'clinical',
    keywords: ['informe', 'historia clinica', 'biopsia', 'diagnostico', 'patologo', 'reporte'],
    render: props => <FaNotesMedical size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'file_medical',
    name: 'Expediente / Protocolo de Autopsia',
    category: 'clinical',
    keywords: ['expediente', 'archivo', 'registro', 'protocolo', 'caso clinico'],
    render: props => <FaFileMedical size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'book_medical',
    name: 'Atlas / Tratado Histológico',
    category: 'clinical',
    keywords: ['libro', 'atlas', 'tratado', 'guia', 'referencia', 'ross', 'junqueira', 'gartner'],
    render: props => <FaBookMedical size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'book_open',
    name: 'Lectura / Marco Teórico',
    category: 'clinical',
    keywords: ['libro', 'abierto', 'estudio', 'guia', 'lectura', 'teoria'],
    render: props => <BookOpen size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'hand_holding_medical',
    name: 'Trasplante / Donación de Tejidos',
    category: 'clinical',
    keywords: ['mano', 'cuidado', 'injerto', 'trasplante', 'donacion', 'tejido'],
    render: props => <FaHandHoldingMedical size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'bandage',
    name: 'Vendaje / Reparación Tisular',
    category: 'clinical',
    keywords: ['vendaje', 'curacion', 'reparacion', 'cicatrizacion', 'fibroblastos', 'herida'],
    render: props => <GiArmBandage size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'map_pin',
    name: 'Ubicación / Marcador Topográfico',
    category: 'clinical',
    keywords: ['pin', 'ubicacion', 'sitio', 'localizacion', 'topografia', 'anatomia', 'map pin'],
    render: props => <MapPin size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'badge_check',
    name: 'Criterio Verificado / Diagnóstico de Certeza',
    category: 'clinical',
    keywords: ['check', 'verificado', 'correcto', 'diagnostico', 'aprobado', 'patognomonico', 'badge'],
    render: props => <BadgeCheck size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'check_circle',
    name: 'Marcador Positivo / Inmunorreactivo',
    category: 'clinical',
    keywords: ['positivo', 'reactivo', 'marcador', 'confirmado', 'check', 'inmuno'],
    render: props => <CheckCircle2 size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'alert_circle',
    name: 'Atipia Celular / Criterio de Sospecha',
    category: 'clinical',
    keywords: ['alerta', 'atipia', 'displasia', 'maligno', 'peligro', 'atencion', 'cuidado'],
    render: props => <AlertCircle size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'star',
    name: 'Tip de Examen / Perla ENARM',
    category: 'clinical',
    keywords: ['estrella', 'examen', 'importante', 'clave', 'enarm', 'evaluacion', 'pregunta frecuente', 'star'],
    render: props => <Star size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'lightbulb',
    name: 'Perla Histológica / Consejo Clínico',
    category: 'clinical',
    keywords: ['bombillo', 'idea', 'perla', 'clave', 'recordar', 'mnemotecnia', 'consejo'],
    render: props => <Lightbulb size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'info',
    name: 'Información / Nota de Cátedra',
    category: 'clinical',
    keywords: ['info', 'informacion', 'nota', 'aclaracion', 'detalle', 'glosario'],
    render: props => <Info size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'fingerprint',
    name: 'Huella Tisular / Perfil Inmunofenotípico',
    category: 'clinical',
    keywords: ['huella', 'identidad', 'diferenciacion', 'perfil', 'inmunofenotipo', 'fingerprint'],
    render: props => <Fingerprint size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'search',
    name: 'Exploración / Búsqueda Panorámica',
    category: 'clinical',
    keywords: ['lupa', 'explorar', 'rastreo', 'busqueda', 'revision de placa', 'search'],
    render: props => <Search size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
  {
    id: 'gauge',
    name: 'Graduación Tisular / Escala Patológica',
    category: 'clinical',
    keywords: ['grado', 'estadio', 'escala', 'presion', 'gleason', 'medidor', 'nivel'],
    render: props => <Gauge size={props.size || 18} color={props.color} className={props.className} style={props.style} />,
  },
];

// Mapa para búsqueda O(1) por id
const ICONS_BY_ID = new Map<string, MedicalIconDefinition>(
  MEDICAL_ICONS_CATALOG.map(icon => [icon.id, icon])
);

interface MedicalIconProps {
  name?: string;
  size?: number;
  color?: string;
  className?: string;
  style?: React.CSSProperties;
  fallback?: React.ReactNode;
}

/**
 * Componente universal que renderiza cualquier ícono médico por ID
 */
export const MedicalIcon: React.FC<MedicalIconProps> = ({
  name,
  size = 18,
  color,
  className,
  style,
  fallback,
}) => {
  if (!name) {
    return fallback ? <>{fallback}</> : <Sparkles size={size} color={color} className={className} style={style} />;
  }

  const cleanName = name.toLowerCase().trim();
  const icon = ICONS_BY_ID.get(cleanName);

  if (icon) {
    return icon.render({ size, color, className, style });
  }

  // Alias comunes de compatibilidad
  if (cleanName.includes('kidney') || cleanName.includes('riñon')) return <GiKidneys size={size} color={color} className={className} style={style} />;
  if (cleanName.includes('lung') || cleanName.includes('pulmon')) return <FaLungs size={size} color={color} className={className} style={style} />;
  if (cleanName.includes('heart') || cleanName.includes('corazon')) return <GiHeartOrgan size={size} color={color} className={className} style={style} />;
  if (cleanName.includes('stomach') || cleanName.includes('estomago')) return <GiStomach size={size} color={color} className={className} style={style} />;
  if (cleanName.includes('liver') || cleanName.includes('higado')) return <GiLiver size={size} color={color} className={className} style={style} />;
  if (cleanName.includes('brain') || cleanName.includes('cerebro')) return <FaBrain size={size} color={color} className={className} style={style} />;
  if (cleanName.includes('bone') || cleanName.includes('hueso')) return <FaBone size={size} color={color} className={className} style={style} />;
  if (cleanName.includes('muscle') || cleanName.includes('musculo')) return <GiMuscleUp size={size} color={color} className={className} style={style} />;
  if (cleanName.includes('filter') || cleanName.includes('filtro')) return <Filter size={size} color={color} className={className} style={style} />;
  if (cleanName.includes('droplet') || cleanName.includes('gota') || cleanName.includes('secrecion')) return <Droplets size={size} color={color} className={className} style={style} />;
  if (cleanName.includes('shield') || cleanName.includes('barrera') || cleanName.includes('proteccion')) return <ShieldCheck size={size} color={color} className={className} style={style} />;
  if (cleanName.includes('zap') || cleanName.includes('rayo') || cleanName.includes('impulso')) return <Zap size={size} color={color} className={className} style={style} />;
  if (cleanName.includes('microscope') || cleanName.includes('microscopio')) return <Microscope size={size} color={color} className={className} style={style} />;
  if (cleanName.includes('flask') || cleanName.includes('matraz')) return <FlaskConical size={size} color={color} className={className} style={style} />;
  if (cleanName.includes('pin') || cleanName.includes('ubicacion')) return <MapPin size={size} color={color} className={className} style={style} />;
  if (cleanName.includes('arrow') || cleanName.includes('intercambio')) return <ArrowRightLeft size={size} color={color} className={className} style={style} />;
  if (cleanName.includes('dna') || cleanName.includes('adn')) return <FaDna size={size} color={color} className={className} style={style} />;
  if (cleanName.includes('star') || cleanName.includes('estrella')) return <Star size={size} color={color} className={className} style={style} />;

  return fallback ? <>{fallback}</> : <Sparkles size={size} color={color} className={className} style={style} />;
};

export default MedicalIcon;
